@echo off
echo Open Watcom Build Environment
SET PATH=g:\WATCOM\BINP;g:\WATCOM\BINW;%PATH%
SET BEGINLIBPATH=g:\WATCOM\BINP\DLL
SET INCLUDE=g:\WATCOM\H;g:\WATCOM\H\OS2;%INCLUDE%
SET WATCOM=g:\WATCOM
SET EDPATH=g:\WATCOM\EDDAT
SET WIPFC=g:\WATCOM\WIPFC
