ECHO OFF
set os2tk=G:\OS2TK45
set BEGINLIBPATH=%OS2TK%\DLL;%BEGINLIBPATH%
set PATH=%OS2TK%\BIN;%PATH%
SET DPATH=%OS2TK%\MSG;%DPATH%
SET HELP=%OS2TK%\HELP;%HELP%
SET BOOKSHELF=%OS2TK%\BOOK;%BOOKSHELF%
SET NLSPATH=%OS2TK%\MSG\%N;%NLSPATH%
SET IPFC=%OS2TK%\IPFC;%IPFC%
rem SET LIB=%OS2TK%\IPFC;%LIB%
REM SET C_INCLUDE_PATH=%OS2TK%/SOM/INCLUDE;%OS2TK%/INC;%OS2TK%/H/GL;%OS2TK%/H;%OS2TK%/H/LIBC;%C_INJCLUDE_PATH%
REM SET CPLUS_INCLUDE_PATH=%OS2TK%/SOM/INCLUDE;%OS2TK%/INC;%OS2TK%/H/GL;%OS2TK%/H;%OS2TK%/H/LIBC;%CPLUS_INJCLUDE_PATH%
rem SET LIBRARY_PATH=%OS2TK%/LIB;%OS2TK%/SOM/LIB;%LIBRARY_PATH%