
/*
 * This file was generated by the SOM Compiler.
 * FileName: WPSSDesktop.h.
 * Generated using:
 *     SOM Precompiler somipc: 2.29.1.17
 *     SOM Emitter emith: 2.47
 */

/*
 * Screen Saver - Lockup Desktop replacement for OS/2 and eComStation systems
 * Copyright (C) 2004-2008 Doodle
 * 
 * Contact: doodle@dont.spam.me.scenergy.dfmk.hu
 * 
 *  This library is free software; you can redistribute it and/or
 *  modify it under the terms of the GNU Lesser General Public
 *  License as published by the Free Software Foundation; either
 *  version 2.1 of the License, or (at your option) any later version.
 * 
 *  This library is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *  Lesser General Public License for more details.
 * 
 *  You should have received a copy of the GNU Lesser General Public
 *  License along with this library; if not, write to the Free Software
 *  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA
 *  02111-1307  USA.
 */


#ifndef SOM_WPSSDesktop_h
#define SOM_WPSSDesktop_h


#include <som.h>

/*
 * -- This emitter treats Method Tokens as Thunks by default.
 * -- Use the sc modifier "nothunks" to change this default
 */
#undef somresolve_
#define somresolve_(obj,mToken) ((somMethodProc*)((void)obj, mToken))

/*
 * Define the class name as an object type
 */
#ifndef WPSSDesktop
#define WPSSDesktop SOMObject
#endif
#include <wpdesk.h>

/*
 * Start of bindings for IDL types
 */

#ifndef SOMClass
    #define SOMClass SOMObject
#endif /* SOMClass */
#ifndef WPFolder
    #define WPFolder SOMObject
#endif /* WPFolder */
#ifndef M_WPObject
    #define M_WPObject SOMObject
#endif /* M_WPObject */
#ifndef WPObject
    #define WPObject SOMObject
#endif /* WPObject */
#ifndef WPImageFile
    #define WPImageFile SOMObject
#endif /* WPImageFile */
#ifndef M_WPFileSystem
    #define M_WPFileSystem SOMObject
#endif /* M_WPFileSystem */
#ifndef M_WPFolder
    #define M_WPFolder SOMObject
#endif /* M_WPFolder */
#ifndef M_WPDesktop
    #define M_WPDesktop SOMObject
#endif /* M_WPDesktop */
#ifndef M_WPSSDesktop
    #define M_WPSSDesktop SOMObject
#endif /* M_WPSSDesktop */
typedef
struct WPSSDesktop_SSMODULEDESC {
char  achSaverDLLFileName[256];
long  lVersionMajor;
long  lVersionMinor;
char  achModuleName[1024];
char  achModuleDesc[4096];
long  bConfigurable;
long  bSupportsPasswordProtection;
} WPSSDesktop_SSMODULEDESC;
typedef
struct WPSSDesktop_SSMODULEDESC* WPSSDesktop_PSSMODULEDESC;

#ifndef SOM_DONT_USE_SHORT_NAMES
#ifndef SOMTGD_SSMODULEDESC
    #ifdef SSMODULEDESC
        #undef SSMODULEDESC
        #define SOMTGD_SSMODULEDESC 1
    #else
        #define SSMODULEDESC WPSSDesktop_SSMODULEDESC
    #endif /* SSMODULEDESC */
#endif /* SOMTGD_SSMODULEDESC */

#ifndef SOM_DONT_USE_SHORT_NAMES
#ifndef SOMTGD_PSSMODULEDESC
    #ifdef PSSMODULEDESC
        #undef PSSMODULEDESC
        #define SOMTGD_PSSMODULEDESC 1
    #else
        #define PSSMODULEDESC WPSSDesktop_PSSMODULEDESC
    #endif /* PSSMODULEDESC */
#endif /* SOMTGD_PSSMODULEDESC */
#endif /* SOM_DONT_USE_SHORT_NAMES */
#endif /* SOM_DONT_USE_SHORT_NAMES */

/*
 * End of bindings for IDL types.
 */

#define WPSSDesktop_MajorVersion 1
#define WPSSDesktop_MinorVersion 2

/*
 * External name shortening if required
 */
#ifdef SOM_USE_SHORT_EXTERNAL_NAMES
#define WPSSDesktopNewClass WPSSDesktopc
#pragma linkage(WPSSDesktopc, system)
#define WPSSDesktopClassData WPSSDesktopd
#define WPSSDesktopCClassData WPSSDesktopx
#endif /* SOM_USE_SHORT_EXTERNAL_NAMES */
/*--------------Migration------------*/
#define WPSSDesktop_classObj WPSSDesktopClassData.classObject
#define _WPSSDesktop WPSSDesktop_classObj

/*
 * Declare the class creation procedure
 */
SOMEXTERN SOMClass * SOMLINK WPSSDesktopNewClass(integer4 somtmajorVersion,
		integer4 somtminorVersion);
#pragma linkage(WPSSDesktopNewClass, system)

/*
 * Declare the class data structure
 */
SOMEXTERN struct WPSSDesktopClassDataStructure {
	SOMClass *classObject;
	somMToken wpssAddScreenSaver1Page;
	somMToken wpssAddScreenSaver2Page;
	somMToken wpssAddScreenSaver3Page;
	somMToken wpssStartScreenSaverNow;
	somMToken wpssStartScreenSaverModulePreview;
	somMToken wpssStopScreenSaverModulePreview;
	somMToken wpssConfigureScreenSaverModule;
	somMToken wpssSetScreenSaverEnabled;
	somMToken wpssQueryScreenSaverEnabled;
	somMToken wpssSetScreenSaverTimeout;
	somMToken wpssQueryScreenSaverTimeout;
	somMToken wpssSetAutoStartAtStartup;
	somMToken wpssQueryAutoStartAtStartup;
	somMToken wpssEncryptScreenSaverPassword;
	somMToken wpssSetScreenSaverPasswordProtected;
	somMToken wpssQueryScreenSaverPasswordProtected;
	somMToken wpssSetScreenSaverEncryptedPassword;
	somMToken wpssQueryScreenSaverEncryptedPassword;
	somMToken wpssSetDelayedPasswordProtection;
	somMToken wpssQueryDelayedPasswordProtection;
	somMToken wpssSetDelayedPasswordProtectionTimeout;
	somMToken wpssQueryDelayedPasswordProtectionTimeout;
	somMToken wpssSetScreenSaverModule;
	somMToken wpssQueryScreenSaverModule;
	somMToken wpssSetScreenSaverPreviewEnabled;
	somMToken wpssQueryScreenSaverPreviewEnabled;
	somMToken wpssQueryNumOfAvailableScreenSaverModules;
	somMToken wpssQueryInfoAboutAvailableScreenSaverModules;
	somMToken wpssSetUseDPMSStandby;
	somMToken wpssQueryUseDPMSStandby;
	somMToken wpssSetDPMSStandbyTimeout;
	somMToken wpssQueryDPMSStandbyTimeout;
	somMToken wpssSetUseDPMSSuspend;
	somMToken wpssQueryUseDPMSSuspend;
	somMToken wpssSetDPMSSuspendTimeout;
	somMToken wpssQueryDPMSSuspendTimeout;
	somMToken wpssSetUseDPMSOff;
	somMToken wpssQueryUseDPMSOff;
	somMToken wpssSetDPMSOffTimeout;
	somMToken wpssQueryDPMSOffTimeout;
	somMToken wpssSetUseCurrentSecurityPassword;
	somMToken wpssQueryUseCurrentSecurityPassword;
	somMToken wpssSetWakeByKeyboardOnly;
	somMToken wpssQueryWakeByKeyboardOnly;
	somMToken wpssSetFirstKeyEventGoesToPwdWindow;
	somMToken wpssQueryFirstKeyEventGoesToPwdWindow;
	somMToken wpssSetDisableVIOPopupsWhileSaving;
	somMToken wpssQueryDisableVIOPopupsWhileSaving;
} SOMDLINK WPSSDesktopClassData;

/*
 * Declare the C specific class data structure
 */
SOMEXTERN struct WPSSDesktopCClassDataStructure {
	somMethodTabs parentMtab;
	somDToken instanceDataToken;
} SOMDLINK WPSSDesktopCClassData;

/*
 * New and Renew macros for WPSSDesktop
 */
#define WPSSDesktopNew() \
   ( _WPSSDesktop ? \
	_somNew(_WPSSDesktop) \
	: ( WPSSDesktopNewClass(\
		WPSSDesktop_MajorVersion, \
		WPSSDesktop_MinorVersion),\
	   _somNew(_WPSSDesktop)))
#define WPSSDesktopRenew(buf) \
   ( _WPSSDesktop ? \
	_somRenew(_WPSSDesktop, buf) \
	: ( WPSSDesktopNewClass(\
		WPSSDesktop_MajorVersion, \
		WPSSDesktop_MinorVersion),\
	   _somRenew(_WPSSDesktop, buf)))

/*
 * Override method: wpSaveState
 */
#define WPSSDesktop_wpSaveState(somSelf) \
	WPObject_wpSaveState(somSelf)

/*
 * Override method: wpRestoreState
 */
#define WPSSDesktop_wpRestoreState(somSelf,ulReserved) \
	WPObject_wpRestoreState(somSelf,ulReserved)

/*
 * Override method: wpAddDesktopLockup1Page
 */
#define WPSSDesktop_wpAddDesktopLockup1Page(somSelf,hwndNotebook) \
	WPDesktop_wpAddDesktopLockup1Page(somSelf,hwndNotebook)

/*
 * Override method: wpAddDesktopLockup2Page
 */
#define WPSSDesktop_wpAddDesktopLockup2Page(somSelf,hwndNotebook) \
	WPDesktop_wpAddDesktopLockup2Page(somSelf,hwndNotebook)

/*
 * Override method: wpAddDesktopLockup3Page
 */
#define WPSSDesktop_wpAddDesktopLockup3Page(somSelf,hwndNotebook) \
	WPDesktop_wpAddDesktopLockup3Page(somSelf,hwndNotebook)

/*
 * Override method: wpSetAutoLockup
 */
#define WPSSDesktop_wpSetAutoLockup(somSelf,bAutoLockup) \
	WPDesktop_wpSetAutoLockup(somSelf,bAutoLockup)

/*
 * Override method: wpSetLockupOnStartup
 */
#define WPSSDesktop_wpSetLockupOnStartup(somSelf,bLockupOnStartup) \
	WPDesktop_wpSetLockupOnStartup(somSelf,bLockupOnStartup)

/*
 * Override method: wpSetup
 */
#define WPSSDesktop_wpSetup(somSelf,pszSetupString) \
	WPObject_wpSetup(somSelf,pszSetupString)

/*
 * Override method: wpMenuItemSelected
 */
#define WPSSDesktop_wpMenuItemSelected(somSelf,hwndFrame,ulMenuId) \
	WPObject_wpMenuItemSelected(somSelf,hwndFrame,ulMenuId)

/*
 * Override method: wpMenuItemHelpSelected
 */
#define WPSSDesktop_wpMenuItemHelpSelected(somSelf,MenuId) \
	WPObject_wpMenuItemHelpSelected(somSelf,MenuId)

/*
 * Override method: wpOpen
 */
#define WPSSDesktop_wpOpen(somSelf,hwndCnr,ulView,param) \
	WPObject_wpOpen(somSelf,hwndCnr,ulView,param)

/*
 * New Method: wpssAddScreenSaver1Page
 */
typedef BOOL   SOMLINK somTP_WPSSDesktop_wpssAddScreenSaver1Page(WPSSDesktop *somSelf, 
		HWND hwndNotebook);
#pragma linkage(somTP_WPSSDesktop_wpssAddScreenSaver1Page, system)
typedef somTP_WPSSDesktop_wpssAddScreenSaver1Page *somTD_WPSSDesktop_wpssAddScreenSaver1Page;
#define somMD_WPSSDesktop_wpssAddScreenSaver1Page "::WPSSDesktop::wpssAddScreenSaver1Page"
#define WPSSDesktop_wpssAddScreenSaver1Page(somSelf,hwndNotebook) \
    (SOM_Resolve(somSelf, WPSSDesktop, wpssAddScreenSaver1Page) \
	(somSelf,hwndNotebook))
#ifndef SOMGD_wpssAddScreenSaver1Page
    #if (defined(_wpssAddScreenSaver1Page) || defined(__wpssAddScreenSaver1Page))
        #undef _wpssAddScreenSaver1Page
        #undef __wpssAddScreenSaver1Page
        #define SOMGD_wpssAddScreenSaver1Page 1
    #else
        #define _wpssAddScreenSaver1Page WPSSDesktop_wpssAddScreenSaver1Page
    #endif /* _wpssAddScreenSaver1Page */
#endif /* SOMGD_wpssAddScreenSaver1Page */

/*
 * New Method: wpssAddScreenSaver2Page
 */
typedef BOOL   SOMLINK somTP_WPSSDesktop_wpssAddScreenSaver2Page(WPSSDesktop *somSelf, 
		HWND hwndNotebook);
#pragma linkage(somTP_WPSSDesktop_wpssAddScreenSaver2Page, system)
typedef somTP_WPSSDesktop_wpssAddScreenSaver2Page *somTD_WPSSDesktop_wpssAddScreenSaver2Page;
#define somMD_WPSSDesktop_wpssAddScreenSaver2Page "::WPSSDesktop::wpssAddScreenSaver2Page"
#define WPSSDesktop_wpssAddScreenSaver2Page(somSelf,hwndNotebook) \
    (SOM_Resolve(somSelf, WPSSDesktop, wpssAddScreenSaver2Page) \
	(somSelf,hwndNotebook))
#ifndef SOMGD_wpssAddScreenSaver2Page
    #if (defined(_wpssAddScreenSaver2Page) || defined(__wpssAddScreenSaver2Page))
        #undef _wpssAddScreenSaver2Page
        #undef __wpssAddScreenSaver2Page
        #define SOMGD_wpssAddScreenSaver2Page 1
    #else
        #define _wpssAddScreenSaver2Page WPSSDesktop_wpssAddScreenSaver2Page
    #endif /* _wpssAddScreenSaver2Page */
#endif /* SOMGD_wpssAddScreenSaver2Page */

/*
 * New Method: wpssAddScreenSaver3Page
 */
typedef BOOL   SOMLINK somTP_WPSSDesktop_wpssAddScreenSaver3Page(WPSSDesktop *somSelf, 
		HWND hwndNotebook);
#pragma linkage(somTP_WPSSDesktop_wpssAddScreenSaver3Page, system)
typedef somTP_WPSSDesktop_wpssAddScreenSaver3Page *somTD_WPSSDesktop_wpssAddScreenSaver3Page;
#define somMD_WPSSDesktop_wpssAddScreenSaver3Page "::WPSSDesktop::wpssAddScreenSaver3Page"
#define WPSSDesktop_wpssAddScreenSaver3Page(somSelf,hwndNotebook) \
    (SOM_Resolve(somSelf, WPSSDesktop, wpssAddScreenSaver3Page) \
	(somSelf,hwndNotebook))
#ifndef SOMGD_wpssAddScreenSaver3Page
    #if (defined(_wpssAddScreenSaver3Page) || defined(__wpssAddScreenSaver3Page))
        #undef _wpssAddScreenSaver3Page
        #undef __wpssAddScreenSaver3Page
        #define SOMGD_wpssAddScreenSaver3Page 1
    #else
        #define _wpssAddScreenSaver3Page WPSSDesktop_wpssAddScreenSaver3Page
    #endif /* _wpssAddScreenSaver3Page */
#endif /* SOMGD_wpssAddScreenSaver3Page */

/*
 * New Method: wpssStartScreenSaverNow
 */
typedef void   SOMLINK somTP_WPSSDesktop_wpssStartScreenSaverNow(WPSSDesktop *somSelf, 
		BOOL bDontDelayPasswordProtection);
#pragma linkage(somTP_WPSSDesktop_wpssStartScreenSaverNow, system)
typedef somTP_WPSSDesktop_wpssStartScreenSaverNow *somTD_WPSSDesktop_wpssStartScreenSaverNow;
#define somMD_WPSSDesktop_wpssStartScreenSaverNow "::WPSSDesktop::wpssStartScreenSaverNow"
#define WPSSDesktop_wpssStartScreenSaverNow(somSelf,bDontDelayPasswordProtection) \
    (SOM_Resolve(somSelf, WPSSDesktop, wpssStartScreenSaverNow) \
	(somSelf,bDontDelayPasswordProtection))
#ifndef SOMGD_wpssStartScreenSaverNow
    #if (defined(_wpssStartScreenSaverNow) || defined(__wpssStartScreenSaverNow))
        #undef _wpssStartScreenSaverNow
        #undef __wpssStartScreenSaverNow
        #define SOMGD_wpssStartScreenSaverNow 1
    #else
        #define _wpssStartScreenSaverNow WPSSDesktop_wpssStartScreenSaverNow
    #endif /* _wpssStartScreenSaverNow */
#endif /* SOMGD_wpssStartScreenSaverNow */

/*
 * New Method: wpssStartScreenSaverModulePreview
 */
typedef void   SOMLINK somTP_WPSSDesktop_wpssStartScreenSaverModulePreview(WPSSDesktop *somSelf, 
		PSZ pszSaverDLLFileName, 
		HWND hwndClientArea);
#pragma linkage(somTP_WPSSDesktop_wpssStartScreenSaverModulePreview, system)
typedef somTP_WPSSDesktop_wpssStartScreenSaverModulePreview *somTD_WPSSDesktop_wpssStartScreenSaverModulePreview;
#define somMD_WPSSDesktop_wpssStartScreenSaverModulePreview "::WPSSDesktop::wpssStartScreenSaverModulePreview"
#define WPSSDesktop_wpssStartScreenSaverModulePreview(somSelf,pszSaverDLLFileName,hwndClientArea) \
    (SOM_Resolve(somSelf, WPSSDesktop, wpssStartScreenSaverModulePreview) \
	(somSelf,pszSaverDLLFileName,hwndClientArea))
#ifndef SOMGD_wpssStartScreenSaverModulePreview
    #if (defined(_wpssStartScreenSaverModulePreview) || defined(__wpssStartScreenSaverModulePreview))
        #undef _wpssStartScreenSaverModulePreview
        #undef __wpssStartScreenSaverModulePreview
        #define SOMGD_wpssStartScreenSaverModulePreview 1
    #else
        #define _wpssStartScreenSaverModulePreview WPSSDesktop_wpssStartScreenSaverModulePreview
    #endif /* _wpssStartScreenSaverModulePreview */
#endif /* SOMGD_wpssStartScreenSaverModulePreview */

/*
 * New Method: wpssStopScreenSaverModulePreview
 */
typedef void   SOMLINK somTP_WPSSDesktop_wpssStopScreenSaverModulePreview(WPSSDesktop *somSelf, 
		HWND hwndClientArea);
#pragma linkage(somTP_WPSSDesktop_wpssStopScreenSaverModulePreview, system)
typedef somTP_WPSSDesktop_wpssStopScreenSaverModulePreview *somTD_WPSSDesktop_wpssStopScreenSaverModulePreview;
#define somMD_WPSSDesktop_wpssStopScreenSaverModulePreview "::WPSSDesktop::wpssStopScreenSaverModulePreview"
#define WPSSDesktop_wpssStopScreenSaverModulePreview(somSelf,hwndClientArea) \
    (SOM_Resolve(somSelf, WPSSDesktop, wpssStopScreenSaverModulePreview) \
	(somSelf,hwndClientArea))
#ifndef SOMGD_wpssStopScreenSaverModulePreview
    #if (defined(_wpssStopScreenSaverModulePreview) || defined(__wpssStopScreenSaverModulePreview))
        #undef _wpssStopScreenSaverModulePreview
        #undef __wpssStopScreenSaverModulePreview
        #define SOMGD_wpssStopScreenSaverModulePreview 1
    #else
        #define _wpssStopScreenSaverModulePreview WPSSDesktop_wpssStopScreenSaverModulePreview
    #endif /* _wpssStopScreenSaverModulePreview */
#endif /* SOMGD_wpssStopScreenSaverModulePreview */

/*
 * New Method: wpssConfigureScreenSaverModule
 */
typedef void   SOMLINK somTP_WPSSDesktop_wpssConfigureScreenSaverModule(WPSSDesktop *somSelf, 
		PSZ pszSaverDLLFileName, 
		HWND hwndOwnerWindow);
#pragma linkage(somTP_WPSSDesktop_wpssConfigureScreenSaverModule, system)
typedef somTP_WPSSDesktop_wpssConfigureScreenSaverModule *somTD_WPSSDesktop_wpssConfigureScreenSaverModule;
#define somMD_WPSSDesktop_wpssConfigureScreenSaverModule "::WPSSDesktop::wpssConfigureScreenSaverModule"
#define WPSSDesktop_wpssConfigureScreenSaverModule(somSelf,pszSaverDLLFileName,hwndOwnerWindow) \
    (SOM_Resolve(somSelf, WPSSDesktop, wpssConfigureScreenSaverModule) \
	(somSelf,pszSaverDLLFileName,hwndOwnerWindow))
#ifndef SOMGD_wpssConfigureScreenSaverModule
    #if (defined(_wpssConfigureScreenSaverModule) || defined(__wpssConfigureScreenSaverModule))
        #undef _wpssConfigureScreenSaverModule
        #undef __wpssConfigureScreenSaverModule
        #define SOMGD_wpssConfigureScreenSaverModule 1
    #else
        #define _wpssConfigureScreenSaverModule WPSSDesktop_wpssConfigureScreenSaverModule
    #endif /* _wpssConfigureScreenSaverModule */
#endif /* SOMGD_wpssConfigureScreenSaverModule */

/*
 * New Method: wpssSetScreenSaverEnabled
 */
typedef void   SOMLINK somTP_WPSSDesktop_wpssSetScreenSaverEnabled(WPSSDesktop *somSelf, 
		BOOL bEnabled);
#pragma linkage(somTP_WPSSDesktop_wpssSetScreenSaverEnabled, system)
typedef somTP_WPSSDesktop_wpssSetScreenSaverEnabled *somTD_WPSSDesktop_wpssSetScreenSaverEnabled;
#define somMD_WPSSDesktop_wpssSetScreenSaverEnabled "::WPSSDesktop::wpssSetScreenSaverEnabled"
#define WPSSDesktop_wpssSetScreenSaverEnabled(somSelf,bEnabled) \
    (SOM_Resolve(somSelf, WPSSDesktop, wpssSetScreenSaverEnabled) \
	(somSelf,bEnabled))
#ifndef SOMGD_wpssSetScreenSaverEnabled
    #if (defined(_wpssSetScreenSaverEnabled) || defined(__wpssSetScreenSaverEnabled))
        #undef _wpssSetScreenSaverEnabled
        #undef __wpssSetScreenSaverEnabled
        #define SOMGD_wpssSetScreenSaverEnabled 1
    #else
        #define _wpssSetScreenSaverEnabled WPSSDesktop_wpssSetScreenSaverEnabled
    #endif /* _wpssSetScreenSaverEnabled */
#endif /* SOMGD_wpssSetScreenSaverEnabled */

/*
 * New Method: wpssQueryScreenSaverEnabled
 */
typedef BOOL   SOMLINK somTP_WPSSDesktop_wpssQueryScreenSaverEnabled(WPSSDesktop *somSelf);
#pragma linkage(somTP_WPSSDesktop_wpssQueryScreenSaverEnabled, system)
typedef somTP_WPSSDesktop_wpssQueryScreenSaverEnabled *somTD_WPSSDesktop_wpssQueryScreenSaverEnabled;
#define somMD_WPSSDesktop_wpssQueryScreenSaverEnabled "::WPSSDesktop::wpssQueryScreenSaverEnabled"
#define WPSSDesktop_wpssQueryScreenSaverEnabled(somSelf) \
    (SOM_Resolve(somSelf, WPSSDesktop, wpssQueryScreenSaverEnabled) \
	(somSelf))
#ifndef SOMGD_wpssQueryScreenSaverEnabled
    #if (defined(_wpssQueryScreenSaverEnabled) || defined(__wpssQueryScreenSaverEnabled))
        #undef _wpssQueryScreenSaverEnabled
        #undef __wpssQueryScreenSaverEnabled
        #define SOMGD_wpssQueryScreenSaverEnabled 1
    #else
        #define _wpssQueryScreenSaverEnabled WPSSDesktop_wpssQueryScreenSaverEnabled
    #endif /* _wpssQueryScreenSaverEnabled */
#endif /* SOMGD_wpssQueryScreenSaverEnabled */

/*
 * New Method: wpssSetScreenSaverTimeout
 */
typedef void   SOMLINK somTP_WPSSDesktop_wpssSetScreenSaverTimeout(WPSSDesktop *somSelf, 
		ULONG ulTimeoutInmsec);
#pragma linkage(somTP_WPSSDesktop_wpssSetScreenSaverTimeout, system)
typedef somTP_WPSSDesktop_wpssSetScreenSaverTimeout *somTD_WPSSDesktop_wpssSetScreenSaverTimeout;
#define somMD_WPSSDesktop_wpssSetScreenSaverTimeout "::WPSSDesktop::wpssSetScreenSaverTimeout"
#define WPSSDesktop_wpssSetScreenSaverTimeout(somSelf,ulTimeoutInmsec) \
    (SOM_Resolve(somSelf, WPSSDesktop, wpssSetScreenSaverTimeout) \
	(somSelf,ulTimeoutInmsec))
#ifndef SOMGD_wpssSetScreenSaverTimeout
    #if (defined(_wpssSetScreenSaverTimeout) || defined(__wpssSetScreenSaverTimeout))
        #undef _wpssSetScreenSaverTimeout
        #undef __wpssSetScreenSaverTimeout
        #define SOMGD_wpssSetScreenSaverTimeout 1
    #else
        #define _wpssSetScreenSaverTimeout WPSSDesktop_wpssSetScreenSaverTimeout
    #endif /* _wpssSetScreenSaverTimeout */
#endif /* SOMGD_wpssSetScreenSaverTimeout */

/*
 * New Method: wpssQueryScreenSaverTimeout
 */
typedef ULONG   SOMLINK somTP_WPSSDesktop_wpssQueryScreenSaverTimeout(WPSSDesktop *somSelf);
#pragma linkage(somTP_WPSSDesktop_wpssQueryScreenSaverTimeout, system)
typedef somTP_WPSSDesktop_wpssQueryScreenSaverTimeout *somTD_WPSSDesktop_wpssQueryScreenSaverTimeout;
#define somMD_WPSSDesktop_wpssQueryScreenSaverTimeout "::WPSSDesktop::wpssQueryScreenSaverTimeout"
#define WPSSDesktop_wpssQueryScreenSaverTimeout(somSelf) \
    (SOM_Resolve(somSelf, WPSSDesktop, wpssQueryScreenSaverTimeout) \
	(somSelf))
#ifndef SOMGD_wpssQueryScreenSaverTimeout
    #if (defined(_wpssQueryScreenSaverTimeout) || defined(__wpssQueryScreenSaverTimeout))
        #undef _wpssQueryScreenSaverTimeout
        #undef __wpssQueryScreenSaverTimeout
        #define SOMGD_wpssQueryScreenSaverTimeout 1
    #else
        #define _wpssQueryScreenSaverTimeout WPSSDesktop_wpssQueryScreenSaverTimeout
    #endif /* _wpssQueryScreenSaverTimeout */
#endif /* SOMGD_wpssQueryScreenSaverTimeout */

/*
 * New Method: wpssSetAutoStartAtStartup
 */
typedef void   SOMLINK somTP_WPSSDesktop_wpssSetAutoStartAtStartup(WPSSDesktop *somSelf, 
		BOOL bAutoStart);
#pragma linkage(somTP_WPSSDesktop_wpssSetAutoStartAtStartup, system)
typedef somTP_WPSSDesktop_wpssSetAutoStartAtStartup *somTD_WPSSDesktop_wpssSetAutoStartAtStartup;
#define somMD_WPSSDesktop_wpssSetAutoStartAtStartup "::WPSSDesktop::wpssSetAutoStartAtStartup"
#define WPSSDesktop_wpssSetAutoStartAtStartup(somSelf,bAutoStart) \
    (SOM_Resolve(somSelf, WPSSDesktop, wpssSetAutoStartAtStartup) \
	(somSelf,bAutoStart))
#ifndef SOMGD_wpssSetAutoStartAtStartup
    #if (defined(_wpssSetAutoStartAtStartup) || defined(__wpssSetAutoStartAtStartup))
        #undef _wpssSetAutoStartAtStartup
        #undef __wpssSetAutoStartAtStartup
        #define SOMGD_wpssSetAutoStartAtStartup 1
    #else
        #define _wpssSetAutoStartAtStartup WPSSDesktop_wpssSetAutoStartAtStartup
    #endif /* _wpssSetAutoStartAtStartup */
#endif /* SOMGD_wpssSetAutoStartAtStartup */

/*
 * New Method: wpssQueryAutoStartAtStartup
 */
typedef BOOL   SOMLINK somTP_WPSSDesktop_wpssQueryAutoStartAtStartup(WPSSDesktop *somSelf);
#pragma linkage(somTP_WPSSDesktop_wpssQueryAutoStartAtStartup, system)
typedef somTP_WPSSDesktop_wpssQueryAutoStartAtStartup *somTD_WPSSDesktop_wpssQueryAutoStartAtStartup;
#define somMD_WPSSDesktop_wpssQueryAutoStartAtStartup "::WPSSDesktop::wpssQueryAutoStartAtStartup"
#define WPSSDesktop_wpssQueryAutoStartAtStartup(somSelf) \
    (SOM_Resolve(somSelf, WPSSDesktop, wpssQueryAutoStartAtStartup) \
	(somSelf))
#ifndef SOMGD_wpssQueryAutoStartAtStartup
    #if (defined(_wpssQueryAutoStartAtStartup) || defined(__wpssQueryAutoStartAtStartup))
        #undef _wpssQueryAutoStartAtStartup
        #undef __wpssQueryAutoStartAtStartup
        #define SOMGD_wpssQueryAutoStartAtStartup 1
    #else
        #define _wpssQueryAutoStartAtStartup WPSSDesktop_wpssQueryAutoStartAtStartup
    #endif /* _wpssQueryAutoStartAtStartup */
#endif /* SOMGD_wpssQueryAutoStartAtStartup */

/*
 * New Method: wpssEncryptScreenSaverPassword
 */
typedef void   SOMLINK somTP_WPSSDesktop_wpssEncryptScreenSaverPassword(WPSSDesktop *somSelf, 
		PSZ pszPassword);
#pragma linkage(somTP_WPSSDesktop_wpssEncryptScreenSaverPassword, system)
typedef somTP_WPSSDesktop_wpssEncryptScreenSaverPassword *somTD_WPSSDesktop_wpssEncryptScreenSaverPassword;
#define somMD_WPSSDesktop_wpssEncryptScreenSaverPassword "::WPSSDesktop::wpssEncryptScreenSaverPassword"
#define WPSSDesktop_wpssEncryptScreenSaverPassword(somSelf,pszPassword) \
    (SOM_Resolve(somSelf, WPSSDesktop, wpssEncryptScreenSaverPassword) \
	(somSelf,pszPassword))
#ifndef SOMGD_wpssEncryptScreenSaverPassword
    #if (defined(_wpssEncryptScreenSaverPassword) || defined(__wpssEncryptScreenSaverPassword))
        #undef _wpssEncryptScreenSaverPassword
        #undef __wpssEncryptScreenSaverPassword
        #define SOMGD_wpssEncryptScreenSaverPassword 1
    #else
        #define _wpssEncryptScreenSaverPassword WPSSDesktop_wpssEncryptScreenSaverPassword
    #endif /* _wpssEncryptScreenSaverPassword */
#endif /* SOMGD_wpssEncryptScreenSaverPassword */

/*
 * New Method: wpssSetScreenSaverPasswordProtected
 */
typedef void   SOMLINK somTP_WPSSDesktop_wpssSetScreenSaverPasswordProtected(WPSSDesktop *somSelf, 
		BOOL bPasswordProtected);
#pragma linkage(somTP_WPSSDesktop_wpssSetScreenSaverPasswordProtected, system)
typedef somTP_WPSSDesktop_wpssSetScreenSaverPasswordProtected *somTD_WPSSDesktop_wpssSetScreenSaverPasswordProtected;
#define somMD_WPSSDesktop_wpssSetScreenSaverPasswordProtected "::WPSSDesktop::wpssSetScreenSaverPasswordProtected"
#define WPSSDesktop_wpssSetScreenSaverPasswordProtected(somSelf,bPasswordProtected) \
    (SOM_Resolve(somSelf, WPSSDesktop, wpssSetScreenSaverPasswordProtected) \
	(somSelf,bPasswordProtected))
#ifndef SOMGD_wpssSetScreenSaverPasswordProtected
    #if (defined(_wpssSetScreenSaverPasswordProtected) || defined(__wpssSetScreenSaverPasswordProtected))
        #undef _wpssSetScreenSaverPasswordProtected
        #undef __wpssSetScreenSaverPasswordProtected
        #define SOMGD_wpssSetScreenSaverPasswordProtected 1
    #else
        #define _wpssSetScreenSaverPasswordProtected WPSSDesktop_wpssSetScreenSaverPasswordProtected
    #endif /* _wpssSetScreenSaverPasswordProtected */
#endif /* SOMGD_wpssSetScreenSaverPasswordProtected */

/*
 * New Method: wpssQueryScreenSaverPasswordProtected
 */
typedef BOOL   SOMLINK somTP_WPSSDesktop_wpssQueryScreenSaverPasswordProtected(WPSSDesktop *somSelf);
#pragma linkage(somTP_WPSSDesktop_wpssQueryScreenSaverPasswordProtected, system)
typedef somTP_WPSSDesktop_wpssQueryScreenSaverPasswordProtected *somTD_WPSSDesktop_wpssQueryScreenSaverPasswordProtected;
#define somMD_WPSSDesktop_wpssQueryScreenSaverPasswordProtected "::WPSSDesktop::wpssQueryScreenSaverPasswordProtected"
#define WPSSDesktop_wpssQueryScreenSaverPasswordProtected(somSelf) \
    (SOM_Resolve(somSelf, WPSSDesktop, wpssQueryScreenSaverPasswordProtected) \
	(somSelf))
#ifndef SOMGD_wpssQueryScreenSaverPasswordProtected
    #if (defined(_wpssQueryScreenSaverPasswordProtected) || defined(__wpssQueryScreenSaverPasswordProtected))
        #undef _wpssQueryScreenSaverPasswordProtected
        #undef __wpssQueryScreenSaverPasswordProtected
        #define SOMGD_wpssQueryScreenSaverPasswordProtected 1
    #else
        #define _wpssQueryScreenSaverPasswordProtected WPSSDesktop_wpssQueryScreenSaverPasswordProtected
    #endif /* _wpssQueryScreenSaverPasswordProtected */
#endif /* SOMGD_wpssQueryScreenSaverPasswordProtected */

/*
 * New Method: wpssSetScreenSaverEncryptedPassword
 */
typedef void   SOMLINK somTP_WPSSDesktop_wpssSetScreenSaverEncryptedPassword(WPSSDesktop *somSelf, 
		PSZ pszEncryptedPassword);
#pragma linkage(somTP_WPSSDesktop_wpssSetScreenSaverEncryptedPassword, system)
typedef somTP_WPSSDesktop_wpssSetScreenSaverEncryptedPassword *somTD_WPSSDesktop_wpssSetScreenSaverEncryptedPassword;
#define somMD_WPSSDesktop_wpssSetScreenSaverEncryptedPassword "::WPSSDesktop::wpssSetScreenSaverEncryptedPassword"
#define WPSSDesktop_wpssSetScreenSaverEncryptedPassword(somSelf,pszEncryptedPassword) \
    (SOM_Resolve(somSelf, WPSSDesktop, wpssSetScreenSaverEncryptedPassword) \
	(somSelf,pszEncryptedPassword))
#ifndef SOMGD_wpssSetScreenSaverEncryptedPassword
    #if (defined(_wpssSetScreenSaverEncryptedPassword) || defined(__wpssSetScreenSaverEncryptedPassword))
        #undef _wpssSetScreenSaverEncryptedPassword
        #undef __wpssSetScreenSaverEncryptedPassword
        #define SOMGD_wpssSetScreenSaverEncryptedPassword 1
    #else
        #define _wpssSetScreenSaverEncryptedPassword WPSSDesktop_wpssSetScreenSaverEncryptedPassword
    #endif /* _wpssSetScreenSaverEncryptedPassword */
#endif /* SOMGD_wpssSetScreenSaverEncryptedPassword */

/*
 * New Method: wpssQueryScreenSaverEncryptedPassword
 */
typedef void   SOMLINK somTP_WPSSDesktop_wpssQueryScreenSaverEncryptedPassword(WPSSDesktop *somSelf, 
		PSZ pszEncryptedPasswordBuf, 
		ULONG ulEncryptedPasswordBufSize);
#pragma linkage(somTP_WPSSDesktop_wpssQueryScreenSaverEncryptedPassword, system)
typedef somTP_WPSSDesktop_wpssQueryScreenSaverEncryptedPassword *somTD_WPSSDesktop_wpssQueryScreenSaverEncryptedPassword;
#define somMD_WPSSDesktop_wpssQueryScreenSaverEncryptedPassword "::WPSSDesktop::wpssQueryScreenSaverEncryptedPassword"
#define WPSSDesktop_wpssQueryScreenSaverEncryptedPassword(somSelf,pszEncryptedPasswordBuf,ulEncryptedPasswordBufSize) \
    (SOM_Resolve(somSelf, WPSSDesktop, wpssQueryScreenSaverEncryptedPassword) \
	(somSelf,pszEncryptedPasswordBuf,ulEncryptedPasswordBufSize))
#ifndef SOMGD_wpssQueryScreenSaverEncryptedPassword
    #if (defined(_wpssQueryScreenSaverEncryptedPassword) || defined(__wpssQueryScreenSaverEncryptedPassword))
        #undef _wpssQueryScreenSaverEncryptedPassword
        #undef __wpssQueryScreenSaverEncryptedPassword
        #define SOMGD_wpssQueryScreenSaverEncryptedPassword 1
    #else
        #define _wpssQueryScreenSaverEncryptedPassword WPSSDesktop_wpssQueryScreenSaverEncryptedPassword
    #endif /* _wpssQueryScreenSaverEncryptedPassword */
#endif /* SOMGD_wpssQueryScreenSaverEncryptedPassword */

/*
 * New Method: wpssSetDelayedPasswordProtection
 */
typedef void   SOMLINK somTP_WPSSDesktop_wpssSetDelayedPasswordProtection(WPSSDesktop *somSelf, 
		BOOL bDelayedPasswordProtection);
#pragma linkage(somTP_WPSSDesktop_wpssSetDelayedPasswordProtection, system)
typedef somTP_WPSSDesktop_wpssSetDelayedPasswordProtection *somTD_WPSSDesktop_wpssSetDelayedPasswordProtection;
#define somMD_WPSSDesktop_wpssSetDelayedPasswordProtection "::WPSSDesktop::wpssSetDelayedPasswordProtection"
#define WPSSDesktop_wpssSetDelayedPasswordProtection(somSelf,bDelayedPasswordProtection) \
    (SOM_Resolve(somSelf, WPSSDesktop, wpssSetDelayedPasswordProtection) \
	(somSelf,bDelayedPasswordProtection))
#ifndef SOMGD_wpssSetDelayedPasswordProtection
    #if (defined(_wpssSetDelayedPasswordProtection) || defined(__wpssSetDelayedPasswordProtection))
        #undef _wpssSetDelayedPasswordProtection
        #undef __wpssSetDelayedPasswordProtection
        #define SOMGD_wpssSetDelayedPasswordProtection 1
    #else
        #define _wpssSetDelayedPasswordProtection WPSSDesktop_wpssSetDelayedPasswordProtection
    #endif /* _wpssSetDelayedPasswordProtection */
#endif /* SOMGD_wpssSetDelayedPasswordProtection */

/*
 * New Method: wpssQueryDelayedPasswordProtection
 */
typedef BOOL   SOMLINK somTP_WPSSDesktop_wpssQueryDelayedPasswordProtection(WPSSDesktop *somSelf);
#pragma linkage(somTP_WPSSDesktop_wpssQueryDelayedPasswordProtection, system)
typedef somTP_WPSSDesktop_wpssQueryDelayedPasswordProtection *somTD_WPSSDesktop_wpssQueryDelayedPasswordProtection;
#define somMD_WPSSDesktop_wpssQueryDelayedPasswordProtection "::WPSSDesktop::wpssQueryDelayedPasswordProtection"
#define WPSSDesktop_wpssQueryDelayedPasswordProtection(somSelf) \
    (SOM_Resolve(somSelf, WPSSDesktop, wpssQueryDelayedPasswordProtection) \
	(somSelf))
#ifndef SOMGD_wpssQueryDelayedPasswordProtection
    #if (defined(_wpssQueryDelayedPasswordProtection) || defined(__wpssQueryDelayedPasswordProtection))
        #undef _wpssQueryDelayedPasswordProtection
        #undef __wpssQueryDelayedPasswordProtection
        #define SOMGD_wpssQueryDelayedPasswordProtection 1
    #else
        #define _wpssQueryDelayedPasswordProtection WPSSDesktop_wpssQueryDelayedPasswordProtection
    #endif /* _wpssQueryDelayedPasswordProtection */
#endif /* SOMGD_wpssQueryDelayedPasswordProtection */

/*
 * New Method: wpssSetDelayedPasswordProtectionTimeout
 */
typedef void   SOMLINK somTP_WPSSDesktop_wpssSetDelayedPasswordProtectionTimeout(WPSSDesktop *somSelf, 
		ULONG ulTimeoutInmsec);
#pragma linkage(somTP_WPSSDesktop_wpssSetDelayedPasswordProtectionTimeout, system)
typedef somTP_WPSSDesktop_wpssSetDelayedPasswordProtectionTimeout *somTD_WPSSDesktop_wpssSetDelayedPasswordProtectionTimeout;
#define somMD_WPSSDesktop_wpssSetDelayedPasswordProtectionTimeout "::WPSSDesktop::wpssSetDelayedPasswordProtectionTimeout"
#define WPSSDesktop_wpssSetDelayedPasswordProtectionTimeout(somSelf,ulTimeoutInmsec) \
    (SOM_Resolve(somSelf, WPSSDesktop, wpssSetDelayedPasswordProtectionTimeout) \
	(somSelf,ulTimeoutInmsec))
#ifndef SOMGD_wpssSetDelayedPasswordProtectionTimeout
    #if (defined(_wpssSetDelayedPasswordProtectionTimeout) || defined(__wpssSetDelayedPasswordProtectionTimeout))
        #undef _wpssSetDelayedPasswordProtectionTimeout
        #undef __wpssSetDelayedPasswordProtectionTimeout
        #define SOMGD_wpssSetDelayedPasswordProtectionTimeout 1
    #else
        #define _wpssSetDelayedPasswordProtectionTimeout WPSSDesktop_wpssSetDelayedPasswordProtectionTimeout
    #endif /* _wpssSetDelayedPasswordProtectionTimeout */
#endif /* SOMGD_wpssSetDelayedPasswordProtectionTimeout */

/*
 * New Method: wpssQueryDelayedPasswordProtectionTimeout
 */
typedef ULONG   SOMLINK somTP_WPSSDesktop_wpssQueryDelayedPasswordProtectionTimeout(WPSSDesktop *somSelf);
#pragma linkage(somTP_WPSSDesktop_wpssQueryDelayedPasswordProtectionTimeout, system)
typedef somTP_WPSSDesktop_wpssQueryDelayedPasswordProtectionTimeout *somTD_WPSSDesktop_wpssQueryDelayedPasswordProtectionTimeout;
#define somMD_WPSSDesktop_wpssQueryDelayedPasswordProtectionTimeout "::WPSSDesktop::wpssQueryDelayedPasswordProtectionTimeout"
#define WPSSDesktop_wpssQueryDelayedPasswordProtectionTimeout(somSelf) \
    (SOM_Resolve(somSelf, WPSSDesktop, wpssQueryDelayedPasswordProtectionTimeout) \
	(somSelf))
#ifndef SOMGD_wpssQueryDelayedPasswordProtectionTimeout
    #if (defined(_wpssQueryDelayedPasswordProtectionTimeout) || defined(__wpssQueryDelayedPasswordProtectionTimeout))
        #undef _wpssQueryDelayedPasswordProtectionTimeout
        #undef __wpssQueryDelayedPasswordProtectionTimeout
        #define SOMGD_wpssQueryDelayedPasswordProtectionTimeout 1
    #else
        #define _wpssQueryDelayedPasswordProtectionTimeout WPSSDesktop_wpssQueryDelayedPasswordProtectionTimeout
    #endif /* _wpssQueryDelayedPasswordProtectionTimeout */
#endif /* SOMGD_wpssQueryDelayedPasswordProtectionTimeout */

/*
 * New Method: wpssSetScreenSaverModule
 */
typedef void   SOMLINK somTP_WPSSDesktop_wpssSetScreenSaverModule(WPSSDesktop *somSelf, 
		PSZ pszSaverDLLFileName);
#pragma linkage(somTP_WPSSDesktop_wpssSetScreenSaverModule, system)
typedef somTP_WPSSDesktop_wpssSetScreenSaverModule *somTD_WPSSDesktop_wpssSetScreenSaverModule;
#define somMD_WPSSDesktop_wpssSetScreenSaverModule "::WPSSDesktop::wpssSetScreenSaverModule"
#define WPSSDesktop_wpssSetScreenSaverModule(somSelf,pszSaverDLLFileName) \
    (SOM_Resolve(somSelf, WPSSDesktop, wpssSetScreenSaverModule) \
	(somSelf,pszSaverDLLFileName))
#ifndef SOMGD_wpssSetScreenSaverModule
    #if (defined(_wpssSetScreenSaverModule) || defined(__wpssSetScreenSaverModule))
        #undef _wpssSetScreenSaverModule
        #undef __wpssSetScreenSaverModule
        #define SOMGD_wpssSetScreenSaverModule 1
    #else
        #define _wpssSetScreenSaverModule WPSSDesktop_wpssSetScreenSaverModule
    #endif /* _wpssSetScreenSaverModule */
#endif /* SOMGD_wpssSetScreenSaverModule */

/*
 * New Method: wpssQueryScreenSaverModule
 */
typedef void   SOMLINK somTP_WPSSDesktop_wpssQueryScreenSaverModule(WPSSDesktop *somSelf, 
		PSZ pszSaverDLLFileNameBuf, 
		ULONG ulSaverDLLFileNameBufSize);
#pragma linkage(somTP_WPSSDesktop_wpssQueryScreenSaverModule, system)
typedef somTP_WPSSDesktop_wpssQueryScreenSaverModule *somTD_WPSSDesktop_wpssQueryScreenSaverModule;
#define somMD_WPSSDesktop_wpssQueryScreenSaverModule "::WPSSDesktop::wpssQueryScreenSaverModule"
#define WPSSDesktop_wpssQueryScreenSaverModule(somSelf,pszSaverDLLFileNameBuf,ulSaverDLLFileNameBufSize) \
    (SOM_Resolve(somSelf, WPSSDesktop, wpssQueryScreenSaverModule) \
	(somSelf,pszSaverDLLFileNameBuf,ulSaverDLLFileNameBufSize))
#ifndef SOMGD_wpssQueryScreenSaverModule
    #if (defined(_wpssQueryScreenSaverModule) || defined(__wpssQueryScreenSaverModule))
        #undef _wpssQueryScreenSaverModule
        #undef __wpssQueryScreenSaverModule
        #define SOMGD_wpssQueryScreenSaverModule 1
    #else
        #define _wpssQueryScreenSaverModule WPSSDesktop_wpssQueryScreenSaverModule
    #endif /* _wpssQueryScreenSaverModule */
#endif /* SOMGD_wpssQueryScreenSaverModule */

/*
 * New Method: wpssSetScreenSaverPreviewEnabled
 */
typedef void   SOMLINK somTP_WPSSDesktop_wpssSetScreenSaverPreviewEnabled(WPSSDesktop *somSelf, 
		BOOL bEnabled);
#pragma linkage(somTP_WPSSDesktop_wpssSetScreenSaverPreviewEnabled, system)
typedef somTP_WPSSDesktop_wpssSetScreenSaverPreviewEnabled *somTD_WPSSDesktop_wpssSetScreenSaverPreviewEnabled;
#define somMD_WPSSDesktop_wpssSetScreenSaverPreviewEnabled "::WPSSDesktop::wpssSetScreenSaverPreviewEnabled"
#define WPSSDesktop_wpssSetScreenSaverPreviewEnabled(somSelf,bEnabled) \
    (SOM_Resolve(somSelf, WPSSDesktop, wpssSetScreenSaverPreviewEnabled) \
	(somSelf,bEnabled))
#ifndef SOMGD_wpssSetScreenSaverPreviewEnabled
    #if (defined(_wpssSetScreenSaverPreviewEnabled) || defined(__wpssSetScreenSaverPreviewEnabled))
        #undef _wpssSetScreenSaverPreviewEnabled
        #undef __wpssSetScreenSaverPreviewEnabled
        #define SOMGD_wpssSetScreenSaverPreviewEnabled 1
    #else
        #define _wpssSetScreenSaverPreviewEnabled WPSSDesktop_wpssSetScreenSaverPreviewEnabled
    #endif /* _wpssSetScreenSaverPreviewEnabled */
#endif /* SOMGD_wpssSetScreenSaverPreviewEnabled */

/*
 * New Method: wpssQueryScreenSaverPreviewEnabled
 */
typedef BOOL   SOMLINK somTP_WPSSDesktop_wpssQueryScreenSaverPreviewEnabled(WPSSDesktop *somSelf);
#pragma linkage(somTP_WPSSDesktop_wpssQueryScreenSaverPreviewEnabled, system)
typedef somTP_WPSSDesktop_wpssQueryScreenSaverPreviewEnabled *somTD_WPSSDesktop_wpssQueryScreenSaverPreviewEnabled;
#define somMD_WPSSDesktop_wpssQueryScreenSaverPreviewEnabled "::WPSSDesktop::wpssQueryScreenSaverPreviewEnabled"
#define WPSSDesktop_wpssQueryScreenSaverPreviewEnabled(somSelf) \
    (SOM_Resolve(somSelf, WPSSDesktop, wpssQueryScreenSaverPreviewEnabled) \
	(somSelf))
#ifndef SOMGD_wpssQueryScreenSaverPreviewEnabled
    #if (defined(_wpssQueryScreenSaverPreviewEnabled) || defined(__wpssQueryScreenSaverPreviewEnabled))
        #undef _wpssQueryScreenSaverPreviewEnabled
        #undef __wpssQueryScreenSaverPreviewEnabled
        #define SOMGD_wpssQueryScreenSaverPreviewEnabled 1
    #else
        #define _wpssQueryScreenSaverPreviewEnabled WPSSDesktop_wpssQueryScreenSaverPreviewEnabled
    #endif /* _wpssQueryScreenSaverPreviewEnabled */
#endif /* SOMGD_wpssQueryScreenSaverPreviewEnabled */

/*
 * New Method: wpssQueryNumOfAvailableScreenSaverModules
 */
typedef ULONG   SOMLINK somTP_WPSSDesktop_wpssQueryNumOfAvailableScreenSaverModules(WPSSDesktop *somSelf);
#pragma linkage(somTP_WPSSDesktop_wpssQueryNumOfAvailableScreenSaverModules, system)
typedef somTP_WPSSDesktop_wpssQueryNumOfAvailableScreenSaverModules *somTD_WPSSDesktop_wpssQueryNumOfAvailableScreenSaverModules;
#define somMD_WPSSDesktop_wpssQueryNumOfAvailableScreenSaverModules "::WPSSDesktop::wpssQueryNumOfAvailableScreenSaverModules"
#define WPSSDesktop_wpssQueryNumOfAvailableScreenSaverModules(somSelf) \
    (SOM_Resolve(somSelf, WPSSDesktop, wpssQueryNumOfAvailableScreenSaverModules) \
	(somSelf))
#ifndef SOMGD_wpssQueryNumOfAvailableScreenSaverModules
    #if (defined(_wpssQueryNumOfAvailableScreenSaverModules) || defined(__wpssQueryNumOfAvailableScreenSaverModules))
        #undef _wpssQueryNumOfAvailableScreenSaverModules
        #undef __wpssQueryNumOfAvailableScreenSaverModules
        #define SOMGD_wpssQueryNumOfAvailableScreenSaverModules 1
    #else
        #define _wpssQueryNumOfAvailableScreenSaverModules WPSSDesktop_wpssQueryNumOfAvailableScreenSaverModules
    #endif /* _wpssQueryNumOfAvailableScreenSaverModules */
#endif /* SOMGD_wpssQueryNumOfAvailableScreenSaverModules */

/*
 * New Method: wpssQueryInfoAboutAvailableScreenSaverModules
 */
typedef ULONG   SOMLINK somTP_WPSSDesktop_wpssQueryInfoAboutAvailableScreenSaverModules(WPSSDesktop *somSelf, 
		ULONG ulMaxModules, 
		WPSSDesktop_PSSMODULEDESC pModuleDescArray);
#pragma linkage(somTP_WPSSDesktop_wpssQueryInfoAboutAvailableScreenSaverModules, system)
typedef somTP_WPSSDesktop_wpssQueryInfoAboutAvailableScreenSaverModules *somTD_WPSSDesktop_wpssQueryInfoAboutAvailableScreenSaverModules;
#define somMD_WPSSDesktop_wpssQueryInfoAboutAvailableScreenSaverModules "::WPSSDesktop::wpssQueryInfoAboutAvailableScreenSaverModules"
#define WPSSDesktop_wpssQueryInfoAboutAvailableScreenSaverModules(somSelf,ulMaxModules,pModuleDescArray) \
    (SOM_Resolve(somSelf, WPSSDesktop, wpssQueryInfoAboutAvailableScreenSaverModules) \
	(somSelf,ulMaxModules,pModuleDescArray))
#ifndef SOMGD_wpssQueryInfoAboutAvailableScreenSaverModules
    #if (defined(_wpssQueryInfoAboutAvailableScreenSaverModules) || defined(__wpssQueryInfoAboutAvailableScreenSaverModules))
        #undef _wpssQueryInfoAboutAvailableScreenSaverModules
        #undef __wpssQueryInfoAboutAvailableScreenSaverModules
        #define SOMGD_wpssQueryInfoAboutAvailableScreenSaverModules 1
    #else
        #define _wpssQueryInfoAboutAvailableScreenSaverModules WPSSDesktop_wpssQueryInfoAboutAvailableScreenSaverModules
    #endif /* _wpssQueryInfoAboutAvailableScreenSaverModules */
#endif /* SOMGD_wpssQueryInfoAboutAvailableScreenSaverModules */

/*
 * New Method: wpssSetUseDPMSStandby
 */
typedef void   SOMLINK somTP_WPSSDesktop_wpssSetUseDPMSStandby(WPSSDesktop *somSelf, 
		BOOL bEnabled);
#pragma linkage(somTP_WPSSDesktop_wpssSetUseDPMSStandby, system)
typedef somTP_WPSSDesktop_wpssSetUseDPMSStandby *somTD_WPSSDesktop_wpssSetUseDPMSStandby;
#define somMD_WPSSDesktop_wpssSetUseDPMSStandby "::WPSSDesktop::wpssSetUseDPMSStandby"
#define WPSSDesktop_wpssSetUseDPMSStandby(somSelf,bEnabled) \
    (SOM_Resolve(somSelf, WPSSDesktop, wpssSetUseDPMSStandby) \
	(somSelf,bEnabled))
#ifndef SOMGD_wpssSetUseDPMSStandby
    #if (defined(_wpssSetUseDPMSStandby) || defined(__wpssSetUseDPMSStandby))
        #undef _wpssSetUseDPMSStandby
        #undef __wpssSetUseDPMSStandby
        #define SOMGD_wpssSetUseDPMSStandby 1
    #else
        #define _wpssSetUseDPMSStandby WPSSDesktop_wpssSetUseDPMSStandby
    #endif /* _wpssSetUseDPMSStandby */
#endif /* SOMGD_wpssSetUseDPMSStandby */

/*
 * New Method: wpssQueryUseDPMSStandby
 */
typedef BOOL   SOMLINK somTP_WPSSDesktop_wpssQueryUseDPMSStandby(WPSSDesktop *somSelf);
#pragma linkage(somTP_WPSSDesktop_wpssQueryUseDPMSStandby, system)
typedef somTP_WPSSDesktop_wpssQueryUseDPMSStandby *somTD_WPSSDesktop_wpssQueryUseDPMSStandby;
#define somMD_WPSSDesktop_wpssQueryUseDPMSStandby "::WPSSDesktop::wpssQueryUseDPMSStandby"
#define WPSSDesktop_wpssQueryUseDPMSStandby(somSelf) \
    (SOM_Resolve(somSelf, WPSSDesktop, wpssQueryUseDPMSStandby) \
	(somSelf))
#ifndef SOMGD_wpssQueryUseDPMSStandby
    #if (defined(_wpssQueryUseDPMSStandby) || defined(__wpssQueryUseDPMSStandby))
        #undef _wpssQueryUseDPMSStandby
        #undef __wpssQueryUseDPMSStandby
        #define SOMGD_wpssQueryUseDPMSStandby 1
    #else
        #define _wpssQueryUseDPMSStandby WPSSDesktop_wpssQueryUseDPMSStandby
    #endif /* _wpssQueryUseDPMSStandby */
#endif /* SOMGD_wpssQueryUseDPMSStandby */

/*
 * New Method: wpssSetDPMSStandbyTimeout
 */
typedef void   SOMLINK somTP_WPSSDesktop_wpssSetDPMSStandbyTimeout(WPSSDesktop *somSelf, 
		ULONG ulTimeoutInmsec);
#pragma linkage(somTP_WPSSDesktop_wpssSetDPMSStandbyTimeout, system)
typedef somTP_WPSSDesktop_wpssSetDPMSStandbyTimeout *somTD_WPSSDesktop_wpssSetDPMSStandbyTimeout;
#define somMD_WPSSDesktop_wpssSetDPMSStandbyTimeout "::WPSSDesktop::wpssSetDPMSStandbyTimeout"
#define WPSSDesktop_wpssSetDPMSStandbyTimeout(somSelf,ulTimeoutInmsec) \
    (SOM_Resolve(somSelf, WPSSDesktop, wpssSetDPMSStandbyTimeout) \
	(somSelf,ulTimeoutInmsec))
#ifndef SOMGD_wpssSetDPMSStandbyTimeout
    #if (defined(_wpssSetDPMSStandbyTimeout) || defined(__wpssSetDPMSStandbyTimeout))
        #undef _wpssSetDPMSStandbyTimeout
        #undef __wpssSetDPMSStandbyTimeout
        #define SOMGD_wpssSetDPMSStandbyTimeout 1
    #else
        #define _wpssSetDPMSStandbyTimeout WPSSDesktop_wpssSetDPMSStandbyTimeout
    #endif /* _wpssSetDPMSStandbyTimeout */
#endif /* SOMGD_wpssSetDPMSStandbyTimeout */

/*
 * New Method: wpssQueryDPMSStandbyTimeout
 */
typedef ULONG   SOMLINK somTP_WPSSDesktop_wpssQueryDPMSStandbyTimeout(WPSSDesktop *somSelf);
#pragma linkage(somTP_WPSSDesktop_wpssQueryDPMSStandbyTimeout, system)
typedef somTP_WPSSDesktop_wpssQueryDPMSStandbyTimeout *somTD_WPSSDesktop_wpssQueryDPMSStandbyTimeout;
#define somMD_WPSSDesktop_wpssQueryDPMSStandbyTimeout "::WPSSDesktop::wpssQueryDPMSStandbyTimeout"
#define WPSSDesktop_wpssQueryDPMSStandbyTimeout(somSelf) \
    (SOM_Resolve(somSelf, WPSSDesktop, wpssQueryDPMSStandbyTimeout) \
	(somSelf))
#ifndef SOMGD_wpssQueryDPMSStandbyTimeout
    #if (defined(_wpssQueryDPMSStandbyTimeout) || defined(__wpssQueryDPMSStandbyTimeout))
        #undef _wpssQueryDPMSStandbyTimeout
        #undef __wpssQueryDPMSStandbyTimeout
        #define SOMGD_wpssQueryDPMSStandbyTimeout 1
    #else
        #define _wpssQueryDPMSStandbyTimeout WPSSDesktop_wpssQueryDPMSStandbyTimeout
    #endif /* _wpssQueryDPMSStandbyTimeout */
#endif /* SOMGD_wpssQueryDPMSStandbyTimeout */

/*
 * New Method: wpssSetUseDPMSSuspend
 */
typedef void   SOMLINK somTP_WPSSDesktop_wpssSetUseDPMSSuspend(WPSSDesktop *somSelf, 
		BOOL bEnabled);
#pragma linkage(somTP_WPSSDesktop_wpssSetUseDPMSSuspend, system)
typedef somTP_WPSSDesktop_wpssSetUseDPMSSuspend *somTD_WPSSDesktop_wpssSetUseDPMSSuspend;
#define somMD_WPSSDesktop_wpssSetUseDPMSSuspend "::WPSSDesktop::wpssSetUseDPMSSuspend"
#define WPSSDesktop_wpssSetUseDPMSSuspend(somSelf,bEnabled) \
    (SOM_Resolve(somSelf, WPSSDesktop, wpssSetUseDPMSSuspend) \
	(somSelf,bEnabled))
#ifndef SOMGD_wpssSetUseDPMSSuspend
    #if (defined(_wpssSetUseDPMSSuspend) || defined(__wpssSetUseDPMSSuspend))
        #undef _wpssSetUseDPMSSuspend
        #undef __wpssSetUseDPMSSuspend
        #define SOMGD_wpssSetUseDPMSSuspend 1
    #else
        #define _wpssSetUseDPMSSuspend WPSSDesktop_wpssSetUseDPMSSuspend
    #endif /* _wpssSetUseDPMSSuspend */
#endif /* SOMGD_wpssSetUseDPMSSuspend */

/*
 * New Method: wpssQueryUseDPMSSuspend
 */
typedef BOOL   SOMLINK somTP_WPSSDesktop_wpssQueryUseDPMSSuspend(WPSSDesktop *somSelf);
#pragma linkage(somTP_WPSSDesktop_wpssQueryUseDPMSSuspend, system)
typedef somTP_WPSSDesktop_wpssQueryUseDPMSSuspend *somTD_WPSSDesktop_wpssQueryUseDPMSSuspend;
#define somMD_WPSSDesktop_wpssQueryUseDPMSSuspend "::WPSSDesktop::wpssQueryUseDPMSSuspend"
#define WPSSDesktop_wpssQueryUseDPMSSuspend(somSelf) \
    (SOM_Resolve(somSelf, WPSSDesktop, wpssQueryUseDPMSSuspend) \
	(somSelf))
#ifndef SOMGD_wpssQueryUseDPMSSuspend
    #if (defined(_wpssQueryUseDPMSSuspend) || defined(__wpssQueryUseDPMSSuspend))
        #undef _wpssQueryUseDPMSSuspend
        #undef __wpssQueryUseDPMSSuspend
        #define SOMGD_wpssQueryUseDPMSSuspend 1
    #else
        #define _wpssQueryUseDPMSSuspend WPSSDesktop_wpssQueryUseDPMSSuspend
    #endif /* _wpssQueryUseDPMSSuspend */
#endif /* SOMGD_wpssQueryUseDPMSSuspend */

/*
 * New Method: wpssSetDPMSSuspendTimeout
 */
typedef void   SOMLINK somTP_WPSSDesktop_wpssSetDPMSSuspendTimeout(WPSSDesktop *somSelf, 
		ULONG ulTimeoutInmsec);
#pragma linkage(somTP_WPSSDesktop_wpssSetDPMSSuspendTimeout, system)
typedef somTP_WPSSDesktop_wpssSetDPMSSuspendTimeout *somTD_WPSSDesktop_wpssSetDPMSSuspendTimeout;
#define somMD_WPSSDesktop_wpssSetDPMSSuspendTimeout "::WPSSDesktop::wpssSetDPMSSuspendTimeout"
#define WPSSDesktop_wpssSetDPMSSuspendTimeout(somSelf,ulTimeoutInmsec) \
    (SOM_Resolve(somSelf, WPSSDesktop, wpssSetDPMSSuspendTimeout) \
	(somSelf,ulTimeoutInmsec))
#ifndef SOMGD_wpssSetDPMSSuspendTimeout
    #if (defined(_wpssSetDPMSSuspendTimeout) || defined(__wpssSetDPMSSuspendTimeout))
        #undef _wpssSetDPMSSuspendTimeout
        #undef __wpssSetDPMSSuspendTimeout
        #define SOMGD_wpssSetDPMSSuspendTimeout 1
    #else
        #define _wpssSetDPMSSuspendTimeout WPSSDesktop_wpssSetDPMSSuspendTimeout
    #endif /* _wpssSetDPMSSuspendTimeout */
#endif /* SOMGD_wpssSetDPMSSuspendTimeout */

/*
 * New Method: wpssQueryDPMSSuspendTimeout
 */
typedef ULONG   SOMLINK somTP_WPSSDesktop_wpssQueryDPMSSuspendTimeout(WPSSDesktop *somSelf);
#pragma linkage(somTP_WPSSDesktop_wpssQueryDPMSSuspendTimeout, system)
typedef somTP_WPSSDesktop_wpssQueryDPMSSuspendTimeout *somTD_WPSSDesktop_wpssQueryDPMSSuspendTimeout;
#define somMD_WPSSDesktop_wpssQueryDPMSSuspendTimeout "::WPSSDesktop::wpssQueryDPMSSuspendTimeout"
#define WPSSDesktop_wpssQueryDPMSSuspendTimeout(somSelf) \
    (SOM_Resolve(somSelf, WPSSDesktop, wpssQueryDPMSSuspendTimeout) \
	(somSelf))
#ifndef SOMGD_wpssQueryDPMSSuspendTimeout
    #if (defined(_wpssQueryDPMSSuspendTimeout) || defined(__wpssQueryDPMSSuspendTimeout))
        #undef _wpssQueryDPMSSuspendTimeout
        #undef __wpssQueryDPMSSuspendTimeout
        #define SOMGD_wpssQueryDPMSSuspendTimeout 1
    #else
        #define _wpssQueryDPMSSuspendTimeout WPSSDesktop_wpssQueryDPMSSuspendTimeout
    #endif /* _wpssQueryDPMSSuspendTimeout */
#endif /* SOMGD_wpssQueryDPMSSuspendTimeout */

/*
 * New Method: wpssSetUseDPMSOff
 */
typedef void   SOMLINK somTP_WPSSDesktop_wpssSetUseDPMSOff(WPSSDesktop *somSelf, 
		BOOL bEnabled);
#pragma linkage(somTP_WPSSDesktop_wpssSetUseDPMSOff, system)
typedef somTP_WPSSDesktop_wpssSetUseDPMSOff *somTD_WPSSDesktop_wpssSetUseDPMSOff;
#define somMD_WPSSDesktop_wpssSetUseDPMSOff "::WPSSDesktop::wpssSetUseDPMSOff"
#define WPSSDesktop_wpssSetUseDPMSOff(somSelf,bEnabled) \
    (SOM_Resolve(somSelf, WPSSDesktop, wpssSetUseDPMSOff) \
	(somSelf,bEnabled))
#ifndef SOMGD_wpssSetUseDPMSOff
    #if (defined(_wpssSetUseDPMSOff) || defined(__wpssSetUseDPMSOff))
        #undef _wpssSetUseDPMSOff
        #undef __wpssSetUseDPMSOff
        #define SOMGD_wpssSetUseDPMSOff 1
    #else
        #define _wpssSetUseDPMSOff WPSSDesktop_wpssSetUseDPMSOff
    #endif /* _wpssSetUseDPMSOff */
#endif /* SOMGD_wpssSetUseDPMSOff */

/*
 * New Method: wpssQueryUseDPMSOff
 */
typedef BOOL   SOMLINK somTP_WPSSDesktop_wpssQueryUseDPMSOff(WPSSDesktop *somSelf);
#pragma linkage(somTP_WPSSDesktop_wpssQueryUseDPMSOff, system)
typedef somTP_WPSSDesktop_wpssQueryUseDPMSOff *somTD_WPSSDesktop_wpssQueryUseDPMSOff;
#define somMD_WPSSDesktop_wpssQueryUseDPMSOff "::WPSSDesktop::wpssQueryUseDPMSOff"
#define WPSSDesktop_wpssQueryUseDPMSOff(somSelf) \
    (SOM_Resolve(somSelf, WPSSDesktop, wpssQueryUseDPMSOff) \
	(somSelf))
#ifndef SOMGD_wpssQueryUseDPMSOff
    #if (defined(_wpssQueryUseDPMSOff) || defined(__wpssQueryUseDPMSOff))
        #undef _wpssQueryUseDPMSOff
        #undef __wpssQueryUseDPMSOff
        #define SOMGD_wpssQueryUseDPMSOff 1
    #else
        #define _wpssQueryUseDPMSOff WPSSDesktop_wpssQueryUseDPMSOff
    #endif /* _wpssQueryUseDPMSOff */
#endif /* SOMGD_wpssQueryUseDPMSOff */

/*
 * New Method: wpssSetDPMSOffTimeout
 */
typedef void   SOMLINK somTP_WPSSDesktop_wpssSetDPMSOffTimeout(WPSSDesktop *somSelf, 
		ULONG ulTimeoutInmsec);
#pragma linkage(somTP_WPSSDesktop_wpssSetDPMSOffTimeout, system)
typedef somTP_WPSSDesktop_wpssSetDPMSOffTimeout *somTD_WPSSDesktop_wpssSetDPMSOffTimeout;
#define somMD_WPSSDesktop_wpssSetDPMSOffTimeout "::WPSSDesktop::wpssSetDPMSOffTimeout"
#define WPSSDesktop_wpssSetDPMSOffTimeout(somSelf,ulTimeoutInmsec) \
    (SOM_Resolve(somSelf, WPSSDesktop, wpssSetDPMSOffTimeout) \
	(somSelf,ulTimeoutInmsec))
#ifndef SOMGD_wpssSetDPMSOffTimeout
    #if (defined(_wpssSetDPMSOffTimeout) || defined(__wpssSetDPMSOffTimeout))
        #undef _wpssSetDPMSOffTimeout
        #undef __wpssSetDPMSOffTimeout
        #define SOMGD_wpssSetDPMSOffTimeout 1
    #else
        #define _wpssSetDPMSOffTimeout WPSSDesktop_wpssSetDPMSOffTimeout
    #endif /* _wpssSetDPMSOffTimeout */
#endif /* SOMGD_wpssSetDPMSOffTimeout */

/*
 * New Method: wpssQueryDPMSOffTimeout
 */
typedef ULONG   SOMLINK somTP_WPSSDesktop_wpssQueryDPMSOffTimeout(WPSSDesktop *somSelf);
#pragma linkage(somTP_WPSSDesktop_wpssQueryDPMSOffTimeout, system)
typedef somTP_WPSSDesktop_wpssQueryDPMSOffTimeout *somTD_WPSSDesktop_wpssQueryDPMSOffTimeout;
#define somMD_WPSSDesktop_wpssQueryDPMSOffTimeout "::WPSSDesktop::wpssQueryDPMSOffTimeout"
#define WPSSDesktop_wpssQueryDPMSOffTimeout(somSelf) \
    (SOM_Resolve(somSelf, WPSSDesktop, wpssQueryDPMSOffTimeout) \
	(somSelf))
#ifndef SOMGD_wpssQueryDPMSOffTimeout
    #if (defined(_wpssQueryDPMSOffTimeout) || defined(__wpssQueryDPMSOffTimeout))
        #undef _wpssQueryDPMSOffTimeout
        #undef __wpssQueryDPMSOffTimeout
        #define SOMGD_wpssQueryDPMSOffTimeout 1
    #else
        #define _wpssQueryDPMSOffTimeout WPSSDesktop_wpssQueryDPMSOffTimeout
    #endif /* _wpssQueryDPMSOffTimeout */
#endif /* SOMGD_wpssQueryDPMSOffTimeout */

/*
 * New Method: wpssSetUseCurrentSecurityPassword
 */
typedef void   SOMLINK somTP_WPSSDesktop_wpssSetUseCurrentSecurityPassword(WPSSDesktop *somSelf, 
		BOOL bEnabled);
#pragma linkage(somTP_WPSSDesktop_wpssSetUseCurrentSecurityPassword, system)
typedef somTP_WPSSDesktop_wpssSetUseCurrentSecurityPassword *somTD_WPSSDesktop_wpssSetUseCurrentSecurityPassword;
#define somMD_WPSSDesktop_wpssSetUseCurrentSecurityPassword "::WPSSDesktop::wpssSetUseCurrentSecurityPassword"
#define WPSSDesktop_wpssSetUseCurrentSecurityPassword(somSelf,bEnabled) \
    (SOM_Resolve(somSelf, WPSSDesktop, wpssSetUseCurrentSecurityPassword) \
	(somSelf,bEnabled))
#ifndef SOMGD_wpssSetUseCurrentSecurityPassword
    #if (defined(_wpssSetUseCurrentSecurityPassword) || defined(__wpssSetUseCurrentSecurityPassword))
        #undef _wpssSetUseCurrentSecurityPassword
        #undef __wpssSetUseCurrentSecurityPassword
        #define SOMGD_wpssSetUseCurrentSecurityPassword 1
    #else
        #define _wpssSetUseCurrentSecurityPassword WPSSDesktop_wpssSetUseCurrentSecurityPassword
    #endif /* _wpssSetUseCurrentSecurityPassword */
#endif /* SOMGD_wpssSetUseCurrentSecurityPassword */

/*
 * New Method: wpssQueryUseCurrentSecurityPassword
 */
typedef BOOL   SOMLINK somTP_WPSSDesktop_wpssQueryUseCurrentSecurityPassword(WPSSDesktop *somSelf);
#pragma linkage(somTP_WPSSDesktop_wpssQueryUseCurrentSecurityPassword, system)
typedef somTP_WPSSDesktop_wpssQueryUseCurrentSecurityPassword *somTD_WPSSDesktop_wpssQueryUseCurrentSecurityPassword;
#define somMD_WPSSDesktop_wpssQueryUseCurrentSecurityPassword "::WPSSDesktop::wpssQueryUseCurrentSecurityPassword"
#define WPSSDesktop_wpssQueryUseCurrentSecurityPassword(somSelf) \
    (SOM_Resolve(somSelf, WPSSDesktop, wpssQueryUseCurrentSecurityPassword) \
	(somSelf))
#ifndef SOMGD_wpssQueryUseCurrentSecurityPassword
    #if (defined(_wpssQueryUseCurrentSecurityPassword) || defined(__wpssQueryUseCurrentSecurityPassword))
        #undef _wpssQueryUseCurrentSecurityPassword
        #undef __wpssQueryUseCurrentSecurityPassword
        #define SOMGD_wpssQueryUseCurrentSecurityPassword 1
    #else
        #define _wpssQueryUseCurrentSecurityPassword WPSSDesktop_wpssQueryUseCurrentSecurityPassword
    #endif /* _wpssQueryUseCurrentSecurityPassword */
#endif /* SOMGD_wpssQueryUseCurrentSecurityPassword */

/*
 * New Method: wpssSetWakeByKeyboardOnly
 */
typedef void   SOMLINK somTP_WPSSDesktop_wpssSetWakeByKeyboardOnly(WPSSDesktop *somSelf, 
		BOOL bEnabled);
#pragma linkage(somTP_WPSSDesktop_wpssSetWakeByKeyboardOnly, system)
typedef somTP_WPSSDesktop_wpssSetWakeByKeyboardOnly *somTD_WPSSDesktop_wpssSetWakeByKeyboardOnly;
#define somMD_WPSSDesktop_wpssSetWakeByKeyboardOnly "::WPSSDesktop::wpssSetWakeByKeyboardOnly"
#define WPSSDesktop_wpssSetWakeByKeyboardOnly(somSelf,bEnabled) \
    (SOM_Resolve(somSelf, WPSSDesktop, wpssSetWakeByKeyboardOnly) \
	(somSelf,bEnabled))
#ifndef SOMGD_wpssSetWakeByKeyboardOnly
    #if (defined(_wpssSetWakeByKeyboardOnly) || defined(__wpssSetWakeByKeyboardOnly))
        #undef _wpssSetWakeByKeyboardOnly
        #undef __wpssSetWakeByKeyboardOnly
        #define SOMGD_wpssSetWakeByKeyboardOnly 1
    #else
        #define _wpssSetWakeByKeyboardOnly WPSSDesktop_wpssSetWakeByKeyboardOnly
    #endif /* _wpssSetWakeByKeyboardOnly */
#endif /* SOMGD_wpssSetWakeByKeyboardOnly */

/*
 * New Method: wpssQueryWakeByKeyboardOnly
 */
typedef BOOL   SOMLINK somTP_WPSSDesktop_wpssQueryWakeByKeyboardOnly(WPSSDesktop *somSelf);
#pragma linkage(somTP_WPSSDesktop_wpssQueryWakeByKeyboardOnly, system)
typedef somTP_WPSSDesktop_wpssQueryWakeByKeyboardOnly *somTD_WPSSDesktop_wpssQueryWakeByKeyboardOnly;
#define somMD_WPSSDesktop_wpssQueryWakeByKeyboardOnly "::WPSSDesktop::wpssQueryWakeByKeyboardOnly"
#define WPSSDesktop_wpssQueryWakeByKeyboardOnly(somSelf) \
    (SOM_Resolve(somSelf, WPSSDesktop, wpssQueryWakeByKeyboardOnly) \
	(somSelf))
#ifndef SOMGD_wpssQueryWakeByKeyboardOnly
    #if (defined(_wpssQueryWakeByKeyboardOnly) || defined(__wpssQueryWakeByKeyboardOnly))
        #undef _wpssQueryWakeByKeyboardOnly
        #undef __wpssQueryWakeByKeyboardOnly
        #define SOMGD_wpssQueryWakeByKeyboardOnly 1
    #else
        #define _wpssQueryWakeByKeyboardOnly WPSSDesktop_wpssQueryWakeByKeyboardOnly
    #endif /* _wpssQueryWakeByKeyboardOnly */
#endif /* SOMGD_wpssQueryWakeByKeyboardOnly */

/*
 * New Method: wpssSetFirstKeyEventGoesToPwdWindow
 */
typedef void   SOMLINK somTP_WPSSDesktop_wpssSetFirstKeyEventGoesToPwdWindow(WPSSDesktop *somSelf, 
		BOOL bEnabled);
#pragma linkage(somTP_WPSSDesktop_wpssSetFirstKeyEventGoesToPwdWindow, system)
typedef somTP_WPSSDesktop_wpssSetFirstKeyEventGoesToPwdWindow *somTD_WPSSDesktop_wpssSetFirstKeyEventGoesToPwdWindow;
#define somMD_WPSSDesktop_wpssSetFirstKeyEventGoesToPwdWindow "::WPSSDesktop::wpssSetFirstKeyEventGoesToPwdWindow"
#define WPSSDesktop_wpssSetFirstKeyEventGoesToPwdWindow(somSelf,bEnabled) \
    (SOM_Resolve(somSelf, WPSSDesktop, wpssSetFirstKeyEventGoesToPwdWindow) \
	(somSelf,bEnabled))
#ifndef SOMGD_wpssSetFirstKeyEventGoesToPwdWindow
    #if (defined(_wpssSetFirstKeyEventGoesToPwdWindow) || defined(__wpssSetFirstKeyEventGoesToPwdWindow))
        #undef _wpssSetFirstKeyEventGoesToPwdWindow
        #undef __wpssSetFirstKeyEventGoesToPwdWindow
        #define SOMGD_wpssSetFirstKeyEventGoesToPwdWindow 1
    #else
        #define _wpssSetFirstKeyEventGoesToPwdWindow WPSSDesktop_wpssSetFirstKeyEventGoesToPwdWindow
    #endif /* _wpssSetFirstKeyEventGoesToPwdWindow */
#endif /* SOMGD_wpssSetFirstKeyEventGoesToPwdWindow */

/*
 * New Method: wpssQueryFirstKeyEventGoesToPwdWindow
 */
typedef BOOL   SOMLINK somTP_WPSSDesktop_wpssQueryFirstKeyEventGoesToPwdWindow(WPSSDesktop *somSelf);
#pragma linkage(somTP_WPSSDesktop_wpssQueryFirstKeyEventGoesToPwdWindow, system)
typedef somTP_WPSSDesktop_wpssQueryFirstKeyEventGoesToPwdWindow *somTD_WPSSDesktop_wpssQueryFirstKeyEventGoesToPwdWindow;
#define somMD_WPSSDesktop_wpssQueryFirstKeyEventGoesToPwdWindow "::WPSSDesktop::wpssQueryFirstKeyEventGoesToPwdWindow"
#define WPSSDesktop_wpssQueryFirstKeyEventGoesToPwdWindow(somSelf) \
    (SOM_Resolve(somSelf, WPSSDesktop, wpssQueryFirstKeyEventGoesToPwdWindow) \
	(somSelf))
#ifndef SOMGD_wpssQueryFirstKeyEventGoesToPwdWindow
    #if (defined(_wpssQueryFirstKeyEventGoesToPwdWindow) || defined(__wpssQueryFirstKeyEventGoesToPwdWindow))
        #undef _wpssQueryFirstKeyEventGoesToPwdWindow
        #undef __wpssQueryFirstKeyEventGoesToPwdWindow
        #define SOMGD_wpssQueryFirstKeyEventGoesToPwdWindow 1
    #else
        #define _wpssQueryFirstKeyEventGoesToPwdWindow WPSSDesktop_wpssQueryFirstKeyEventGoesToPwdWindow
    #endif /* _wpssQueryFirstKeyEventGoesToPwdWindow */
#endif /* SOMGD_wpssQueryFirstKeyEventGoesToPwdWindow */

/*
 * New Method: wpssSetDisableVIOPopupsWhileSaving
 */
typedef void   SOMLINK somTP_WPSSDesktop_wpssSetDisableVIOPopupsWhileSaving(WPSSDesktop *somSelf, 
		BOOL bVIOPopupsDisabled);
#pragma linkage(somTP_WPSSDesktop_wpssSetDisableVIOPopupsWhileSaving, system)
typedef somTP_WPSSDesktop_wpssSetDisableVIOPopupsWhileSaving *somTD_WPSSDesktop_wpssSetDisableVIOPopupsWhileSaving;
#define somMD_WPSSDesktop_wpssSetDisableVIOPopupsWhileSaving "::WPSSDesktop::wpssSetDisableVIOPopupsWhileSaving"
#define WPSSDesktop_wpssSetDisableVIOPopupsWhileSaving(somSelf,bVIOPopupsDisabled) \
    (SOM_Resolve(somSelf, WPSSDesktop, wpssSetDisableVIOPopupsWhileSaving) \
	(somSelf,bVIOPopupsDisabled))
#ifndef SOMGD_wpssSetDisableVIOPopupsWhileSaving
    #if (defined(_wpssSetDisableVIOPopupsWhileSaving) || defined(__wpssSetDisableVIOPopupsWhileSaving))
        #undef _wpssSetDisableVIOPopupsWhileSaving
        #undef __wpssSetDisableVIOPopupsWhileSaving
        #define SOMGD_wpssSetDisableVIOPopupsWhileSaving 1
    #else
        #define _wpssSetDisableVIOPopupsWhileSaving WPSSDesktop_wpssSetDisableVIOPopupsWhileSaving
    #endif /* _wpssSetDisableVIOPopupsWhileSaving */
#endif /* SOMGD_wpssSetDisableVIOPopupsWhileSaving */

/*
 * New Method: wpssQueryDisableVIOPopupsWhileSaving
 */
typedef BOOL   SOMLINK somTP_WPSSDesktop_wpssQueryDisableVIOPopupsWhileSaving(WPSSDesktop *somSelf);
#pragma linkage(somTP_WPSSDesktop_wpssQueryDisableVIOPopupsWhileSaving, system)
typedef somTP_WPSSDesktop_wpssQueryDisableVIOPopupsWhileSaving *somTD_WPSSDesktop_wpssQueryDisableVIOPopupsWhileSaving;
#define somMD_WPSSDesktop_wpssQueryDisableVIOPopupsWhileSaving "::WPSSDesktop::wpssQueryDisableVIOPopupsWhileSaving"
#define WPSSDesktop_wpssQueryDisableVIOPopupsWhileSaving(somSelf) \
    (SOM_Resolve(somSelf, WPSSDesktop, wpssQueryDisableVIOPopupsWhileSaving) \
	(somSelf))
#ifndef SOMGD_wpssQueryDisableVIOPopupsWhileSaving
    #if (defined(_wpssQueryDisableVIOPopupsWhileSaving) || defined(__wpssQueryDisableVIOPopupsWhileSaving))
        #undef _wpssQueryDisableVIOPopupsWhileSaving
        #undef __wpssQueryDisableVIOPopupsWhileSaving
        #define SOMGD_wpssQueryDisableVIOPopupsWhileSaving 1
    #else
        #define _wpssQueryDisableVIOPopupsWhileSaving WPSSDesktop_wpssQueryDisableVIOPopupsWhileSaving
    #endif /* _wpssQueryDisableVIOPopupsWhileSaving */
#endif /* SOMGD_wpssQueryDisableVIOPopupsWhileSaving */
#ifndef SOM_DONT_USE_INHERITED_MACROS
#define WPSSDesktop_wpIsCurrentDesktop WPDesktop_wpIsCurrentDesktop
#define WPSSDesktop_wpAddDesktopArcRest1Page WPDesktop_wpAddDesktopArcRest1Page
#define WPSSDesktop_wpAddDesktopDefDT1Page WPDesktop_wpAddDesktopDefDT1Page
#define WPSSDesktop_wpQueryDefaultDropOp WPDesktop_wpQueryDefaultDropOp
#define WPSSDesktop_wpSetDefaultDropOp WPDesktop_wpSetDefaultDropOp
#define WPSSDesktop_wpQueryAutoLockup WPDesktop_wpQueryAutoLockup
#define WPSSDesktop_wpQueryLockupTimeout WPDesktop_wpQueryLockupTimeout
#define WPSSDesktop_wpSetLockupTimeout WPDesktop_wpSetLockupTimeout
#define WPSSDesktop_wpQueryLockupOnStartup WPDesktop_wpQueryLockupOnStartup
#define WPSSDesktop_wpQueryLockupFullScreen WPDesktop_wpQueryLockupFullScreen
#define WPSSDesktop_wpSetLockupFullScreen WPDesktop_wpSetLockupFullScreen
#define WPSSDesktop_wpQueryLockupAutoDim WPDesktop_wpQueryLockupAutoDim
#define WPSSDesktop_wpSetLockupAutoDim WPDesktop_wpSetLockupAutoDim
#define WPSSDesktop_wpQueryLockupBackground WPDesktop_wpQueryLockupBackground
#define WPSSDesktop_wpSetLockupBackground WPDesktop_wpSetLockupBackground
#define WPSSDesktop_wpInitData WPObject_wpInitData
#define WPSSDesktop_wpAddSettingsPages WPObject_wpAddSettingsPages
#define WPSSDesktop_wpFilterMenu WPObject_wpFilterMenu
#define WPSSDesktop_wpModifyMenu WPObject_wpModifyMenu
#define WPSSDesktop_somDefaultInit SOMObject_somDefaultInit
#define WPSSDesktop_somDestruct SOMObject_somDestruct
#define WPSSDesktop_wpPopulate WPFolder_wpPopulate
#define WPSSDesktop_wpSetFldrFlags WPFolder_wpSetFldrFlags
#define WPSSDesktop_wpQueryFldrFlags WPFolder_wpQueryFldrFlags
#define WPSSDesktop_wpSetFldrFont WPFolder_wpSetFldrFont
#define WPSSDesktop_wpQueryFldrFont WPFolder_wpQueryFldrFont
#define WPSSDesktop_wpSetFldrAttr WPFolder_wpSetFldrAttr
#define WPSSDesktop_wpQueryFldrAttr WPFolder_wpQueryFldrAttr
#define WPSSDesktop_wpSetNextIconPos WPFolder_wpSetNextIconPos
#define WPSSDesktop_wpQueryNextIconPos WPFolder_wpQueryNextIconPos
#define WPSSDesktop_wpQueryContent WPFolder_wpQueryContent
#define WPSSDesktop_wpAddFolderView1Page WPFolder_wpAddFolderView1Page
#define WPSSDesktop_wpAddFolderView2Page WPFolder_wpAddFolderView2Page
#define WPSSDesktop_wpAddFolderView3Page WPFolder_wpAddFolderView3Page
#define WPSSDesktop_wpAddFolderIncludePage WPFolder_wpAddFolderIncludePage
#define WPSSDesktop_wpAddFolderSortPage WPFolder_wpAddFolderSortPage
#define WPSSDesktop_wpAddFolderBackgroundPage WPFolder_wpAddFolderBackgroundPage
#define WPSSDesktop_wpAddFolderMenu2Page WPFolder_wpAddFolderMenu2Page
#define WPSSDesktop_wpAddFolderSelfClosePage WPFolder_wpAddFolderSelfClosePage
#define WPSSDesktop_wpInitIconPosData WPFolder_wpInitIconPosData
#define WPSSDesktop_wpFreeIconPosData WPFolder_wpFreeIconPosData
#define WPSSDesktop_wpStoreIconPosData WPFolder_wpStoreIconPosData
#define WPSSDesktop_wpQueryIconPosition WPFolder_wpQueryIconPosition
#define WPSSDesktop_wpSetFldrSort WPFolder_wpSetFldrSort
#define WPSSDesktop_wpQueryFldrSort WPFolder_wpQueryFldrSort
#define WPSSDesktop_wpRestoreFldrRunObjs WPFolder_wpRestoreFldrRunObjs
#define WPSSDesktop_wpStoreFldrRunObjs WPFolder_wpStoreFldrRunObjs
#define WPSSDesktop_wpHideFldrRunObjs WPFolder_wpHideFldrRunObjs
#define WPSSDesktop_wpDeleteContents WPFolder_wpDeleteContents
#define WPSSDesktop_wpSetFldrDetailsClass WPFolder_wpSetFldrDetailsClass
#define WPSSDesktop_wpQueryFldrDetailsClass WPFolder_wpQueryFldrDetailsClass
#define WPSSDesktop_wpSearchFolder WPFolder_wpSearchFolder
#define WPSSDesktop_wpContainsFolders WPFolder_wpContainsFolders
#define WPSSDesktop_wpQueryOpenFolders WPFolder_wpQueryOpenFolders
#define WPSSDesktop_wpModifyFldrFlags WPFolder_wpModifyFldrFlags
#define WPSSDesktop_wpAddToContent WPFolder_wpAddToContent
#define WPSSDesktop_wpDeleteFromContent WPFolder_wpDeleteFromContent
#define WPSSDesktop_wpSetDetailsColumnVisibility WPFolder_wpSetDetailsColumnVisibility
#define WPSSDesktop_wpIsDetailsColumnVisible WPFolder_wpIsDetailsColumnVisible
#define WPSSDesktop_wpSetFldrSortClass WPFolder_wpSetFldrSortClass
#define WPSSDesktop_wpQueryFldrSortClass WPFolder_wpQueryFldrSortClass
#define WPSSDesktop_wpSetSortAttribAvailable WPFolder_wpSetSortAttribAvailable
#define WPSSDesktop_wpIsSortAttribAvailable WPFolder_wpIsSortAttribAvailable
#define WPSSDesktop_wpQueryIconViewPos WPFolder_wpQueryIconViewPos
#define WPSSDesktop_wpAddFirstChild WPFolder_wpAddFirstChild
#define WPSSDesktop_wpFlushNotifications WPFolder_wpFlushNotifications
#define WPSSDesktop_wpSetMenuBarVisibility WPFolder_wpSetMenuBarVisibility
#define WPSSDesktop_wpQueryMenuBarVisibility WPFolder_wpQueryMenuBarVisibility
#define WPSSDesktop_wpQueryIconTextBackgroundColor WPFolder_wpQueryIconTextBackgroundColor
#define WPSSDesktop_wpSetIconTextBackgroundColor WPFolder_wpSetIconTextBackgroundColor
#define WPSSDesktop_wpQueryIconTextColor WPFolder_wpQueryIconTextColor
#define WPSSDesktop_wpSetIconTextColor WPFolder_wpSetIconTextColor
#define WPSSDesktop_wpQueryShadowTextColor WPFolder_wpQueryShadowTextColor
#define WPSSDesktop_wpSetShadowTextColor WPFolder_wpSetShadowTextColor
#define WPSSDesktop_wpQueryIconTextVisibility WPFolder_wpQueryIconTextVisibility
#define WPSSDesktop_wpSetIconTextVisibility WPFolder_wpSetIconTextVisibility
#define WPSSDesktop_wpQueryFldrBackground WPFolder_wpQueryFldrBackground
#define WPSSDesktop_wpSetFldrBackground WPFolder_wpSetFldrBackground
#define WPSSDesktop_wpUnInitData WPObject_wpUnInitData
#define WPSSDesktop_wpFree WPObject_wpFree
#define WPSSDesktop_wpDelete WPObject_wpDelete
#define WPSSDesktop_wpConfirmDelete WPObject_wpConfirmDelete
#define WPSSDesktop_wpMoveObject WPObject_wpMoveObject
#define WPSSDesktop_wpDrop WPObject_wpDrop
#define WPSSDesktop_wpDragOver WPObject_wpDragOver
#define WPSSDesktop_wpAddFile3Page WPFileSystem_wpAddFile3Page
#define WPSSDesktop_wpAddFile2Page WPFileSystem_wpAddFile2Page
#define WPSSDesktop_wpFormatDragItem WPObject_wpFormatDragItem
#define WPSSDesktop_wpRender WPObject_wpRender
#define WPSSDesktop_wpRefresh WPFileSystem_wpRefresh
#define WPSSDesktop_wpQueryDefaultView WPObject_wpQueryDefaultView
#define WPSSDesktop_wpRenderComplete WPObject_wpRenderComplete
#define WPSSDesktop_wpAddFileMenuPage WPFileSystem_wpAddFileMenuPage
#define WPSSDesktop_wpQueryDefaultHelp WPObject_wpQueryDefaultHelp
#define WPSSDesktop_wpObjectReady WPObject_wpObjectReady
#define WPSSDesktop_wpAddObjectWindowPage WPObject_wpAddObjectWindowPage
#define WPSSDesktop_wpDisplayMenu WPObject_wpDisplayMenu
#define WPSSDesktop_wpSetIconData WPObject_wpSetIconData
#define WPSSDesktop_wpSetRealName WPFileSystem_wpSetRealName
#define WPSSDesktop_wpSetType WPFileSystem_wpSetType
#define WPSSDesktop_wpQueryType WPFileSystem_wpQueryType
#define WPSSDesktop_wpSetAttr WPFileSystem_wpSetAttr
#define WPSSDesktop_wpQueryAttr WPFileSystem_wpQueryAttr
#define WPSSDesktop_wpAddFile1Page WPFileSystem_wpAddFile1Page
#define WPSSDesktop_wpQueryCreation WPFileSystem_wpQueryCreation
#define WPSSDesktop_wpQueryLastAccess WPFileSystem_wpQueryLastAccess
#define WPSSDesktop_wpQueryLastWrite WPFileSystem_wpQueryLastWrite
#define WPSSDesktop_wpQueryFileSize WPFileSystem_wpQueryFileSize
#define WPSSDesktop_wpQueryEASize WPFileSystem_wpQueryEASize
#define WPSSDesktop_wpSetDateInfo WPFileSystem_wpSetDateInfo
#define WPSSDesktop_wpSetFileSizeInfo WPFileSystem_wpSetFileSizeInfo
#define WPSSDesktop_wpQueryRefreshFlags WPFileSystem_wpQueryRefreshFlags
#define WPSSDesktop_wpSetRefreshFlags WPFileSystem_wpSetRefreshFlags
#define WPSSDesktop_wpPrintPlainTextFile WPFileSystem_wpPrintPlainTextFile
#define WPSSDesktop_wpSetTitleAndRenameFile WPFileSystem_wpSetTitleAndRenameFile
#define WPSSDesktop_wpConfirmRenameFileWithExt WPFileSystem_wpConfirmRenameFileWithExt
#define WPSSDesktop_wpVerifyUpdateAccess WPFileSystem_wpVerifyUpdateAccess
#define WPSSDesktop_wpQueryEASupport WPFileSystem_wpQueryEASupport
#define WPSSDesktop_wpAddUserItemsToPopupMenu WPFileSystem_wpAddUserItemsToPopupMenu
#define WPSSDesktop_wpIsDiskSwapped WPFileSystem_wpIsDiskSwapped
#define WPSSDesktop_wpQueryRealName WPFileSystem_wpQueryRealName
#define WPSSDesktop_wpQueryFilename WPFileSystem_wpQueryFilename
#define WPSSDesktop_wpQueryDisk WPFileSystem_wpQueryDisk
#define WPSSDesktop_wpQueryDateInfo WPFileSystem_wpQueryDateInfo
#define WPSSDesktop_wpConfirmKeepAssoc WPFileSystem_wpConfirmKeepAssoc
#define WPSSDesktop_wpQueryFileSizeL WPFileSystem_wpQueryFileSizeL
#define WPSSDesktop_wpSetFileSizeL WPFileSystem_wpSetFileSizeL
#define WPSSDesktop_wpQueryHandle WPObject_wpQueryHandle
#define WPSSDesktop_wpSaveImmediate WPObject_wpSaveImmediate
#define WPSSDesktop_wpSetTitle WPObject_wpSetTitle
#define WPSSDesktop_wpViewObject WPObject_wpViewObject
#define WPSSDesktop_wpSwitchTo WPObject_wpSwitchTo
#define WPSSDesktop_wpCopyObject WPObject_wpCopyObject
#define WPSSDesktop_wpCreateFromTemplate WPObject_wpCreateFromTemplate
#define WPSSDesktop_wpQueryIcon WPObject_wpQueryIcon
#define WPSSDesktop_wpQueryIconData WPObject_wpQueryIconData
#define WPSSDesktop_wpQueryDetailsData WPObject_wpQueryDetailsData
#define WPSSDesktop_wpDraggedOverObject WPObject_wpDraggedOverObject
#define WPSSDesktop_wpDroppedOnObject WPObject_wpDroppedOnObject
#define WPSSDesktop_wpQueryNameClashOptions WPObject_wpQueryNameClashOptions
#define WPSSDesktop_wpAppendObject WPObject_wpAppendObject
#define WPSSDesktop_wpReplaceObject WPObject_wpReplaceObject
#define WPSSDesktop_wpQueryStyle WPObject_wpQueryStyle
#define WPSSDesktop_wpDoesObjectMatch WPObject_wpDoesObjectMatch
#define WPSSDesktop_wpIdentify WPObject_wpIdentify
#define WPSSDesktop_wpIsDeleteable WPObject_wpIsDeleteable
#define WPSSDesktop_wpAddObjectGeneralPage WPObject_wpAddObjectGeneralPage
#define WPSSDesktop_wpAddObjectGeneralPage2 WPObject_wpAddObjectGeneralPage2
#define WPSSDesktop_wpAddToObjUseList WPObject_wpAddToObjUseList
#define WPSSDesktop_wpAllocMem WPObject_wpAllocMem
#define WPSSDesktop_wpAssertObjectMutexSem WPObject_wpAssertObjectMutexSem
#define WPSSDesktop_wpClose WPObject_wpClose
#define WPSSDesktop_wpCnrInsertObject WPObject_wpCnrInsertObject
#define WPSSDesktop_wpCnrRemoveObject WPObject_wpCnrRemoveObject
#define WPSSDesktop_wpCnrSetEmphasis WPObject_wpCnrSetEmphasis
#define WPSSDesktop_wpConfirmObjectTitle WPObject_wpConfirmObjectTitle
#define WPSSDesktop_wpCopiedFromTemplate WPObject_wpCopiedFromTemplate
#define WPSSDesktop_wpCreateAnother WPObject_wpCreateAnother
#define WPSSDesktop_wpCreateShadowObject WPObject_wpCreateShadowObject
#define WPSSDesktop_wpDeleteFromObjUseList WPObject_wpDeleteFromObjUseList
#define WPSSDesktop_wpDisplayHelp WPObject_wpDisplayHelp
#define WPSSDesktop_wpEndConversation WPObject_wpEndConversation
#define WPSSDesktop_wpFilterPopupMenu WPObject_wpFilterPopupMenu
#define WPSSDesktop_wpFindUseItem WPObject_wpFindUseItem
#define WPSSDesktop_wpFreeMem WPObject_wpFreeMem
#define WPSSDesktop_wpHide WPObject_wpHide
#define WPSSDesktop_wpInsertPopupMenuItems WPObject_wpInsertPopupMenuItems
#define WPSSDesktop_wpInsertMenuItems WPObject_wpInsertMenuItems
#define WPSSDesktop_wpInsertSettingsPage WPObject_wpInsertSettingsPage
#define WPSSDesktop_wpModifyPopupMenu WPObject_wpModifyPopupMenu
#define WPSSDesktop_wpPrintObject WPObject_wpPrintObject
#define WPSSDesktop_wpQueryConcurrentView WPObject_wpQueryConcurrentView
#define WPSSDesktop_wpQueryButtonAppearance WPObject_wpQueryButtonAppearance
#define WPSSDesktop_wpQueryConfirmations WPObject_wpQueryConfirmations
#define WPSSDesktop_wpQueryError WPObject_wpQueryError
#define WPSSDesktop_wpSetFolder WPObject_wpSetFolder
#define WPSSDesktop_wpQueryFolder WPObject_wpQueryFolder
#define WPSSDesktop_wpQueryMinWindow WPObject_wpQueryMinWindow
#define WPSSDesktop_wpSetTaskRec WPObject_wpSetTaskRec
#define WPSSDesktop_wpFindTaskRec WPObject_wpFindTaskRec
#define WPSSDesktop_wpQueryTitle WPObject_wpQueryTitle
#define WPSSDesktop_wpRegisterView WPObject_wpRegisterView
#define WPSSDesktop_wpReleaseObjectMutexSem WPObject_wpReleaseObjectMutexSem
#define WPSSDesktop_wpRequestObjectMutexSem WPObject_wpRequestObjectMutexSem
#define WPSSDesktop_wpRestore WPObject_wpRestore
#define WPSSDesktop_wpRestoreData WPObject_wpRestoreData
#define WPSSDesktop_wpRestoreLong WPObject_wpRestoreLong
#define WPSSDesktop_wpRestoreString WPObject_wpRestoreString
#define WPSSDesktop_wpSaveData WPObject_wpSaveData
#define WPSSDesktop_wpSaveDeferred WPObject_wpSaveDeferred
#define WPSSDesktop_wpSaveLong WPObject_wpSaveLong
#define WPSSDesktop_wpSaveString WPObject_wpSaveString
#define WPSSDesktop_wpScanSetupString WPObject_wpScanSetupString
#define WPSSDesktop_wpSetConcurrentView WPObject_wpSetConcurrentView
#define WPSSDesktop_wpSetButtonAppearance WPObject_wpSetButtonAppearance
#define WPSSDesktop_wpSetDefaultHelp WPObject_wpSetDefaultHelp
#define WPSSDesktop_wpSetDefaultView WPObject_wpSetDefaultView
#define WPSSDesktop_wpSetError WPObject_wpSetError
#define WPSSDesktop_wpQueryScreenGroupID WPObject_wpQueryScreenGroupID
#define WPSSDesktop_wpSetupOnce WPObject_wpSetupOnce
#define WPSSDesktop_wpSetIcon WPObject_wpSetIcon
#define WPSSDesktop_wpSetMinWindow WPObject_wpSetMinWindow
#define WPSSDesktop_wpModifyStyle WPObject_wpModifyStyle
#define WPSSDesktop_wpQueryTrueStyle WPObject_wpQueryTrueStyle
#define WPSSDesktop_wpUnlockObject WPObject_wpUnlockObject
#define WPSSDesktop_wpIsObjectInitialized WPObject_wpIsObjectInitialized
#define WPSSDesktop_wpCreateShadowObjectExt WPObject_wpCreateShadowObjectExt
#define WPSSDesktop_wpCnrDeleteUseItem WPObject_wpCnrDeleteUseItem
#define WPSSDesktop_wpQueryCoreRecord WPObject_wpQueryCoreRecord
#define WPSSDesktop_wpSetObjectID WPObject_wpSetObjectID
#define WPSSDesktop_wpQueryObjectID WPObject_wpQueryObjectID
#define WPSSDesktop_wpSetDefaultIconPos WPObject_wpSetDefaultIconPos
#define WPSSDesktop_wpQueryDefaultIconPos WPObject_wpQueryDefaultIconPos
#define WPSSDesktop_wpCnrRefreshDetails WPObject_wpCnrRefreshDetails
#define WPSSDesktop_wpFindViewItem WPObject_wpFindViewItem
#define WPSSDesktop_wpLockObject WPObject_wpLockObject
#define WPSSDesktop_wpIsLocked WPObject_wpIsLocked
#define WPSSDesktop_wpQueryContainerFlagPtr WPObject_wpQueryContainerFlagPtr
#define WPSSDesktop_wpWaitForClose WPObject_wpWaitForClose
#define WPSSDesktop_wpSetMenuStyle WPObject_wpSetMenuStyle
#define WPSSDesktop_wpQueryMenuStyle WPObject_wpQueryMenuStyle
#define WPSSDesktop_wpSetStyle WPObject_wpSetStyle
#define WPSSDesktop_somInit SOMObject_somInit
#define WPSSDesktop_somUninit SOMObject_somUninit
#define WPSSDesktop_somDefaultCopyInit SOMObject_somDefaultCopyInit
#define WPSSDesktop_somDefaultAssign SOMObject_somDefaultAssign
#define WPSSDesktop_somDefaultConstCopyInit SOMObject_somDefaultConstCopyInit
#define WPSSDesktop_somDefaultVCopyInit SOMObject_somDefaultVCopyInit
#define WPSSDesktop_somDefaultConstVCopyInit SOMObject_somDefaultConstVCopyInit
#define WPSSDesktop_somDefaultConstAssign SOMObject_somDefaultConstAssign
#define WPSSDesktop_somDefaultVAssign SOMObject_somDefaultVAssign
#define WPSSDesktop_somDefaultConstVAssign SOMObject_somDefaultConstVAssign
#define WPSSDesktop_somFree SOMObject_somFree
#define WPSSDesktop_somGetClass SOMObject_somGetClass
#define WPSSDesktop_somGetClassName SOMObject_somGetClassName
#define WPSSDesktop_somGetSize SOMObject_somGetSize
#define WPSSDesktop_somIsA SOMObject_somIsA
#define WPSSDesktop_somIsInstanceOf SOMObject_somIsInstanceOf
#define WPSSDesktop_somRespondsTo SOMObject_somRespondsTo
#define WPSSDesktop_somDispatch SOMObject_somDispatch
#define WPSSDesktop_somClassDispatch SOMObject_somClassDispatch
#define WPSSDesktop_somCastObj SOMObject_somCastObj
#define WPSSDesktop_somResetObj SOMObject_somResetObj
#define WPSSDesktop_somDispatchV SOMObject_somDispatchV
#define WPSSDesktop_somDispatchL SOMObject_somDispatchL
#define WPSSDesktop_somDispatchA SOMObject_somDispatchA
#define WPSSDesktop_somDispatchD SOMObject_somDispatchD
#define WPSSDesktop_somPrintSelf SOMObject_somPrintSelf
#define WPSSDesktop_somDumpSelf SOMObject_somDumpSelf
#define WPSSDesktop_somDumpSelfInt SOMObject_somDumpSelfInt
#endif /* SOM_DONT_USE_INHERITED_MACROS */

#endif       /* SOM_WPSSDesktop_h */

#ifndef SOM_M_WPSSDesktop_h
#define SOM_M_WPSSDesktop_h


#include <som.h>

/*
 * -- This emitter treats Method Tokens as Thunks by default.
 * -- Use the sc modifier "nothunks" to change this default
 */
#undef somresolve_
#define somresolve_(obj,mToken) ((somMethodProc*)((void)obj, mToken))

/*
 * Define the class name as an object type
 */
#ifndef M_WPSSDesktop
#define M_WPSSDesktop SOMObject
#endif
#include <wpdesk.h>

/*
 * Start of bindings for IDL types
 */


/*
 * End of bindings for IDL types.
 */

#define M_WPSSDesktop_MajorVersion 1
#define M_WPSSDesktop_MinorVersion 2

/*
 * External name shortening if required
 */
#ifdef SOM_USE_SHORT_EXTERNAL_NAMES
#define M_WPSSDesktopNewClass WPSSDesktopc
#pragma linkage(WPSSDesktopc, system)
#define M_WPSSDesktopClassData WPSSDesktopd
#define M_WPSSDesktopCClassData WPSSDesktopx
#endif /* SOM_USE_SHORT_EXTERNAL_NAMES */
/*--------------Migration------------*/
#define M_WPSSDesktop_classObj M_WPSSDesktopClassData.classObject
#define _M_WPSSDesktop M_WPSSDesktop_classObj

/*
 * Declare the class creation procedure
 */
SOMEXTERN SOMClass * SOMLINK M_WPSSDesktopNewClass(integer4 somtmajorVersion,
		integer4 somtminorVersion);
#pragma linkage(M_WPSSDesktopNewClass, system)

/*
 * Declare the class data structure
 */
SOMEXTERN struct M_WPSSDesktopClassDataStructure {
	SOMClass *classObject;
	somMToken wpssclsInitializeScreenSaver;
	somMToken wpssclsUninitializeScreenSaver;
} SOMDLINK M_WPSSDesktopClassData;

/*
 * Declare the C specific class data structure
 */
SOMEXTERN struct M_WPSSDesktopCClassDataStructure {
	somMethodTabs parentMtab;
	somDToken instanceDataToken;
} SOMDLINK M_WPSSDesktopCClassData;

/*
 * New and Renew macros for M_WPSSDesktop
 */
#define M_WPSSDesktopNew() \
   ( _M_WPSSDesktop ? \
	_somNew(_M_WPSSDesktop) \
	: ( M_WPSSDesktopNewClass(\
		M_WPSSDesktop_MajorVersion, \
		M_WPSSDesktop_MinorVersion),\
	   _somNew(_M_WPSSDesktop)))
#define M_WPSSDesktopRenew(buf) \
   ( _M_WPSSDesktop ? \
	_somRenew(_M_WPSSDesktop, buf) \
	: ( M_WPSSDesktopNewClass(\
		M_WPSSDesktop_MajorVersion, \
		M_WPSSDesktop_MinorVersion),\
	   _somRenew(_M_WPSSDesktop, buf)))

/*
 * Override method: wpclsInitData
 */
#define M_WPSSDesktop_wpclsInitData(somSelf) \
	M_WPObject_wpclsInitData(somSelf)

/*
 * Override method: wpclsUnInitData
 */
#define M_WPSSDesktop_wpclsUnInitData(somSelf) \
	M_WPObject_wpclsUnInitData(somSelf)

/*
 * Override method: wpclsQueryTitle
 */
#define M_WPSSDesktop_wpclsQueryTitle(somSelf) \
	M_WPObject_wpclsQueryTitle(somSelf)

/*
 * Override method: wpclsQuerySettingsPageSize
 */
#define M_WPSSDesktop_wpclsQuerySettingsPageSize(somSelf,pSizl) \
	M_WPObject_wpclsQuerySettingsPageSize(somSelf,pSizl)

/*
 * New Method: wpssclsInitializeScreenSaver
 */
typedef BOOL   SOMLINK somTP_M_WPSSDesktop_wpssclsInitializeScreenSaver(M_WPSSDesktop *somSelf);
#pragma linkage(somTP_M_WPSSDesktop_wpssclsInitializeScreenSaver, system)
typedef somTP_M_WPSSDesktop_wpssclsInitializeScreenSaver *somTD_M_WPSSDesktop_wpssclsInitializeScreenSaver;
#define somMD_M_WPSSDesktop_wpssclsInitializeScreenSaver "::M_WPSSDesktop::wpssclsInitializeScreenSaver"
#define M_WPSSDesktop_wpssclsInitializeScreenSaver(somSelf) \
    (SOM_Resolve(somSelf, M_WPSSDesktop, wpssclsInitializeScreenSaver) \
	(somSelf))
#ifndef SOMGD_wpssclsInitializeScreenSaver
    #if (defined(_wpssclsInitializeScreenSaver) || defined(__wpssclsInitializeScreenSaver))
        #undef _wpssclsInitializeScreenSaver
        #undef __wpssclsInitializeScreenSaver
        #define SOMGD_wpssclsInitializeScreenSaver 1
    #else
        #define _wpssclsInitializeScreenSaver M_WPSSDesktop_wpssclsInitializeScreenSaver
    #endif /* _wpssclsInitializeScreenSaver */
#endif /* SOMGD_wpssclsInitializeScreenSaver */

/*
 * New Method: wpssclsUninitializeScreenSaver
 */
typedef BOOL   SOMLINK somTP_M_WPSSDesktop_wpssclsUninitializeScreenSaver(M_WPSSDesktop *somSelf);
#pragma linkage(somTP_M_WPSSDesktop_wpssclsUninitializeScreenSaver, system)
typedef somTP_M_WPSSDesktop_wpssclsUninitializeScreenSaver *somTD_M_WPSSDesktop_wpssclsUninitializeScreenSaver;
#define somMD_M_WPSSDesktop_wpssclsUninitializeScreenSaver "::M_WPSSDesktop::wpssclsUninitializeScreenSaver"
#define M_WPSSDesktop_wpssclsUninitializeScreenSaver(somSelf) \
    (SOM_Resolve(somSelf, M_WPSSDesktop, wpssclsUninitializeScreenSaver) \
	(somSelf))
#ifndef SOMGD_wpssclsUninitializeScreenSaver
    #if (defined(_wpssclsUninitializeScreenSaver) || defined(__wpssclsUninitializeScreenSaver))
        #undef _wpssclsUninitializeScreenSaver
        #undef __wpssclsUninitializeScreenSaver
        #define SOMGD_wpssclsUninitializeScreenSaver 1
    #else
        #define _wpssclsUninitializeScreenSaver M_WPSSDesktop_wpssclsUninitializeScreenSaver
    #endif /* _wpssclsUninitializeScreenSaver */
#endif /* SOMGD_wpssclsUninitializeScreenSaver */
#ifndef SOM_DONT_USE_INHERITED_MACROS
#define M_WPSSDesktop_wpclsQueryObjectFromFrame M_WPDesktop_wpclsQueryObjectFromFrame
#define M_WPSSDesktop_wpclsQueryActiveDesktopHWND M_WPDesktop_wpclsQueryActiveDesktopHWND
#define M_WPSSDesktop_wpclsQueryActiveDesktop M_WPDesktop_wpclsQueryActiveDesktop
#define M_WPSSDesktop_wpclsQueryDefaultView M_WPObject_wpclsQueryDefaultView
#define M_WPSSDesktop_wpclsQueryIconData M_WPObject_wpclsQueryIconData
#define M_WPSSDesktop_wpclsQueryIconDataN M_WPFolder_wpclsQueryIconDataN
#define M_WPSSDesktop_wpclsQueryStyle M_WPObject_wpclsQueryStyle
#define M_WPSSDesktop_wpclsQueryDefaultHelp M_WPObject_wpclsQueryDefaultHelp
#define M_WPSSDesktop_wpclsQueryIconN M_WPFolder_wpclsQueryIconN
#define M_WPSSDesktop_wpclsQueryOpenFolders M_WPFolder_wpclsQueryOpenFolders
#define M_WPSSDesktop_wpclsQueryAwakeObject M_WPFileSystem_wpclsQueryAwakeObject
#define M_WPSSDesktop_wpclsFileSysExists M_WPFileSystem_wpclsFileSysExists
#define M_WPSSDesktop_wpclsQueryObjectFromPath M_WPFileSystem_wpclsQueryObjectFromPath
#define M_WPSSDesktop_wpclsQueryInstanceType M_WPFileSystem_wpclsQueryInstanceType
#define M_WPSSDesktop_wpclsQueryInstanceFilter M_WPFileSystem_wpclsQueryInstanceFilter
#define M_WPSSDesktop_wpclsQueryInstanceClass M_WPFileSystem_wpclsQueryInstanceClass
#define M_WPSSDesktop_wpclsQueryDetailsInfo M_WPObject_wpclsQueryDetailsInfo
#define M_WPSSDesktop_wpclsQuerySearchInfo M_WPObject_wpclsQuerySearchInfo
#define M_WPSSDesktop_wpclsQueryExtendedCriteria M_WPObject_wpclsQueryExtendedCriteria
#define M_WPSSDesktop_wpclsNew M_WPObject_wpclsNew
#define M_WPSSDesktop_wpclsObjectFromHandle M_WPObject_wpclsObjectFromHandle
#define M_WPSSDesktop_wpclsCreateDefaultTemplates M_WPObject_wpclsCreateDefaultTemplates
#define M_WPSSDesktop_wpclsMakeAwake M_WPObject_wpclsMakeAwake
#define M_WPSSDesktop_wpclsQueryDetails M_WPObject_wpclsQueryDetails
#define M_WPSSDesktop_wpclsQueryFolder M_WPObject_wpclsQueryFolder
#define M_WPSSDesktop_wpclsQueryIcon M_WPObject_wpclsQueryIcon
#define M_WPSSDesktop_wpclsFindObjectFirst M_WPObject_wpclsFindObjectFirst
#define M_WPSSDesktop_wpclsFindObjectNext M_WPObject_wpclsFindObjectNext
#define M_WPSSDesktop_wpclsFindObjectEnd M_WPObject_wpclsFindObjectEnd
#define M_WPSSDesktop_wpclsSetError M_WPObject_wpclsSetError
#define M_WPSSDesktop_wpclsQueryError M_WPObject_wpclsQueryError
#define M_WPSSDesktop_wpclsQueryObject M_WPObject_wpclsQueryObject
#define M_WPSSDesktop_wpclsQueryButtonAppearance M_WPObject_wpclsQueryButtonAppearance
#define M_WPSSDesktop_wpclsDecUsage M_WPObject_wpclsDecUsage
#define M_WPSSDesktop_wpclsIncUsage M_WPObject_wpclsIncUsage
#define M_WPSSDesktop_wpclsInsertMultipleObjects M_WPObject_wpclsInsertMultipleObjects
#define M_WPSSDesktop_wpclsFindOneObject M_WPObject_wpclsFindOneObject
#define M_WPSSDesktop_wpclsSetSettingsPageSize M_WPObject_wpclsSetSettingsPageSize
#define M_WPSSDesktop_wpclsSetIconData M_WPObject_wpclsSetIconData
#define M_WPSSDesktop_wpclsSetIcon M_WPObject_wpclsSetIcon
#define M_WPSSDesktop_wpclsRemoveObjects M_WPObject_wpclsRemoveObjects
#define M_WPSSDesktop_somUninit SOMObject_somUninit
#define M_WPSSDesktop_somClassReady SOMClass_somClassReady
#define M_WPSSDesktop_somNew SOMClass_somNew
#define M_WPSSDesktop_somRenew SOMClass_somRenew
#define M_WPSSDesktop__get_somDataAlignment SOMClass__get_somDataAlignment
#define M_WPSSDesktop__get_somInstanceDataOffsets SOMClass__get_somInstanceDataOffsets
#define M_WPSSDesktop__get_somDirectInitClasses SOMClass__get_somDirectInitClasses
#define M_WPSSDesktop_somNewNoInit SOMClass_somNewNoInit
#define M_WPSSDesktop_somRenewNoInit SOMClass_somRenewNoInit
#define M_WPSSDesktop_somRenewNoZero SOMClass_somRenewNoZero
#define M_WPSSDesktop_somRenewNoInitNoZero SOMClass_somRenewNoInitNoZero
#define M_WPSSDesktop_somAllocate SOMClass_somAllocate
#define M_WPSSDesktop_somDeallocate SOMClass_somDeallocate
#define M_WPSSDesktop_somInitClass SOMClass_somInitClass
#define M_WPSSDesktop_somInitMIClass SOMClass_somInitMIClass
#define M_WPSSDesktop_somAddStaticMethod SOMClass_somAddStaticMethod
#define M_WPSSDesktop_somAddDynamicMethod SOMClass_somAddDynamicMethod
#define M_WPSSDesktop_somOverrideSMethod SOMClass_somOverrideSMethod
#define M_WPSSDesktop_somGetApplyStub SOMClass_somGetApplyStub
#define M_WPSSDesktop_somGetClassData SOMClass_somGetClassData
#define M_WPSSDesktop_somSetClassData SOMClass_somSetClassData
#define M_WPSSDesktop_somGetClassMtab SOMClass_somGetClassMtab
#define M_WPSSDesktop_somGetInstanceOffset SOMClass_somGetInstanceOffset
#define M_WPSSDesktop_somGetInstancePartSize SOMClass_somGetInstancePartSize
#define M_WPSSDesktop_somGetInstanceSize SOMClass_somGetInstanceSize
#define M_WPSSDesktop_somGetInstanceToken SOMClass_somGetInstanceToken
#define M_WPSSDesktop_somGetMemberToken SOMClass_somGetMemberToken
#define M_WPSSDesktop_somGetMethodData SOMClass_somGetMethodData
#define M_WPSSDesktop_somGetRdStub SOMClass_somGetRdStub
#define M_WPSSDesktop_somGetMethodDescriptor SOMClass_somGetMethodDescriptor
#define M_WPSSDesktop_somGetMethodIndex SOMClass_somGetMethodIndex
#define M_WPSSDesktop_somGetMethodToken SOMClass_somGetMethodToken
#define M_WPSSDesktop_somGetName SOMClass_somGetName
#define M_WPSSDesktop_somGetNthMethodData SOMClass_somGetNthMethodData
#define M_WPSSDesktop_somGetNthMethodInfo SOMClass_somGetNthMethodInfo
#define M_WPSSDesktop_somGetNumMethods SOMClass_somGetNumMethods
#define M_WPSSDesktop_somGetNumStaticMethods SOMClass_somGetNumStaticMethods
#define M_WPSSDesktop_somGetParent SOMClass_somGetParent
#define M_WPSSDesktop_somGetParents SOMClass_somGetParents
#define M_WPSSDesktop_somGetVersionNumbers SOMClass_somGetVersionNumbers
#define M_WPSSDesktop_somFindMethod SOMClass_somFindMethod
#define M_WPSSDesktop_somFindMethodOk SOMClass_somFindMethodOk
#define M_WPSSDesktop_somFindSMethod SOMClass_somFindSMethod
#define M_WPSSDesktop_somFindSMethodOk SOMClass_somFindSMethodOk
#define M_WPSSDesktop_somLookupMethod SOMClass_somLookupMethod
#define M_WPSSDesktop_somCheckVersion SOMClass_somCheckVersion
#define M_WPSSDesktop_somDescendedFrom SOMClass_somDescendedFrom
#define M_WPSSDesktop_somSupportsMethod SOMClass_somSupportsMethod
#define M_WPSSDesktop_somDefinedMethod SOMClass_somDefinedMethod
#define M_WPSSDesktop_somOverrideMtab SOMClass_somOverrideMtab
#define M_WPSSDesktop_somDefaultInit SOMObject_somDefaultInit
#define M_WPSSDesktop_somDestruct SOMObject_somDestruct
#define M_WPSSDesktop_somDefaultCopyInit SOMObject_somDefaultCopyInit
#define M_WPSSDesktop_somDefaultAssign SOMObject_somDefaultAssign
#define M_WPSSDesktop_somDefaultConstCopyInit SOMObject_somDefaultConstCopyInit
#define M_WPSSDesktop_somDefaultVCopyInit SOMObject_somDefaultVCopyInit
#define M_WPSSDesktop_somDefaultConstVCopyInit SOMObject_somDefaultConstVCopyInit
#define M_WPSSDesktop_somDefaultConstAssign SOMObject_somDefaultConstAssign
#define M_WPSSDesktop_somDefaultVAssign SOMObject_somDefaultVAssign
#define M_WPSSDesktop_somDefaultConstVAssign SOMObject_somDefaultConstVAssign
#define M_WPSSDesktop_somInit SOMObject_somInit
#define M_WPSSDesktop_somFree SOMObject_somFree
#define M_WPSSDesktop_somGetClass SOMObject_somGetClass
#define M_WPSSDesktop_somGetClassName SOMObject_somGetClassName
#define M_WPSSDesktop_somGetSize SOMObject_somGetSize
#define M_WPSSDesktop_somIsA SOMObject_somIsA
#define M_WPSSDesktop_somIsInstanceOf SOMObject_somIsInstanceOf
#define M_WPSSDesktop_somRespondsTo SOMObject_somRespondsTo
#define M_WPSSDesktop_somDispatch SOMObject_somDispatch
#define M_WPSSDesktop_somClassDispatch SOMObject_somClassDispatch
#define M_WPSSDesktop_somCastObj SOMObject_somCastObj
#define M_WPSSDesktop_somResetObj SOMObject_somResetObj
#define M_WPSSDesktop_somDispatchV SOMObject_somDispatchV
#define M_WPSSDesktop_somDispatchL SOMObject_somDispatchL
#define M_WPSSDesktop_somDispatchA SOMObject_somDispatchA
#define M_WPSSDesktop_somDispatchD SOMObject_somDispatchD
#define M_WPSSDesktop_somPrintSelf SOMObject_somPrintSelf
#define M_WPSSDesktop_somDumpSelf SOMObject_somDumpSelf
#define M_WPSSDesktop_somDumpSelfInt SOMObject_somDumpSelfInt
#endif /* SOM_DONT_USE_INHERITED_MACROS */

#endif       /* SOM_M_WPSSDesktop_h */
